{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.1805.0 (23.12)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Agristat dim_clmn\",\"Agristat dim_mm_tm\",\"Agristat dim_run_group\",\"Agristat lgcy_report\",\"Agristat lgcy_sprog\",\"Agristat plnt_alias\",\"Agristat live_mm_fact\",\"Agristat live_mm_fact AGROSUPER AA\",\"Agristat lot_mult_mm_fact\",\"Maestra Indice\",\"Maestra Vivo\",\"Dólar Banco central\",\"Dólar Banco central 2018 a 2020\",\"Dólar Banco central AA\",\"Dólar Banco central AA 2017 - 2020\",\"Filtro Comparación\",\"Filtro Cascada\",\"Fechas de libros en SQL\",\"Maestra Industrial\",\"Indice Industrial Pollo\",\"Indice Industrial Cerdo\",\"Usuario\",\"OrdenIndice\",\"Orden Indice AA\",\"Orden Indice AA CERDO\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBI_RemovedChildren",
        "value": "[{\"remoteItemId\":{\"foreignKeyRelationship\":{\"fromTableLocalLineageTag\":\"2796414d-97e7-467f-8e8c-45d3d9b63229\",\"fromColumnLocalLineageTag\":\"abc4a03a-1878-452e-b159-39c94d7cc284\",\"toTableLocalLineageTag\":\"3ca4b595-438b-4824-836d-28a97cc9e6e7\",\"toColumnLocalLineageTag\":\"f18ddaf2-8f9c-4a50-8683-75f49467d086\"}},\"objectType\":\"Relationship\"}]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "es-ES",
    "cultures": [
      {
        "name": "es-ES",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "fastCombine": true,
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "b8643cd9-5492-4a6d-b679-a3e05d995e5f",
        "fromColumn": "Fecha Libro",
        "fromTable": "Agristat dim_mm_tm",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a416ded6-dca5-4204-8c9f-c9f8737ed22c"
      },
      {
        "name": "76df0829-de47-4ba1-8975-be4f67c3b574",
        "fromColumn": "last_db_updt_ts",
        "fromTable": "Agristat dim_mm_tm",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_9fd41813-3cbb-41be-900d-e8f01ff89716"
      },
      {
        "name": "6e6840b5-df89-4e54-ae56-939431f2f151",
        "fromColumn": "last_db_updt_ts",
        "fromTable": "Agristat dim_run_group",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_64526ce3-9f69-4e05-a1ae-ee3a71915ef9"
      },
      {
        "name": "36b7aab5-7328-4108-92d1-0ec7785f61da",
        "fromColumn": "last_db_updt_ts",
        "fromTable": "Agristat lgcy_report",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_90bf2604-53f0-4c0d-b9b0-d1c91892761d"
      },
      {
        "name": "975af22b-f76a-4c77-bbd4-9a02e86c155e",
        "fromColumn": "last_db_updt_ts",
        "fromTable": "Agristat lgcy_sprog",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a917c58e-4e9b-4816-8090-23d8ac4cd422"
      },
      {
        "name": "433c51e5-c5c7-427d-9ac5-251536a2338a",
        "fromColumn": "last_db_updt_ts",
        "fromTable": "Agristat live_mm_fact",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_67a10a6a-6e8d-4348-aef2-26425e82f0be"
      },
      {
        "name": "f6f06400-cbdf-4e3e-970b-a4ef618a4659",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "lgcy_rpt_id",
        "fromTable": "Agristat dim_clmn",
        "toColumn": "lgcy_rpt_id",
        "toTable": "Agristat lgcy_report"
      },
      {
        "name": "4892b9fc-ee77-461b-b5a2-a60aff3fb79d",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "clmn_id",
        "fromTable": "Agristat live_mm_fact",
        "toColumn": "clmn_id",
        "toTable": "Agristat dim_clmn"
      },
      {
        "name": "26500e60-7673-4f5f-9da2-d5e5072aae96",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "mm_tm_id",
        "fromTable": "Agristat live_mm_fact",
        "toColumn": "mm_tm_id",
        "toTable": "Agristat dim_mm_tm"
      },
      {
        "name": "daa51dc6-d495-4d1f-b979-bd2b4209fa90",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "run_grp_id",
        "fromTable": "Agristat live_mm_fact",
        "toColumn": "run_grp_id",
        "toTable": "Agristat dim_run_group"
      },
      {
        "name": "29e68e58-6ee5-4674-a1ae-b3eab7d2d646",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "lgcy_sprog_id",
        "fromTable": "Agristat lgcy_report",
        "toColumn": "lgcy_sprog_id",
        "toTable": "Agristat lgcy_sprog"
      },
      {
        "name": "c3d956b7-c59f-4b07-ab5c-80e7ec3631ae",
        "fromColumn": "Cruce Maestra",
        "fromTable": "Agristat live_mm_fact",
        "toColumn": "Cruce Maestra",
        "toTable": "Maestra Indice"
      },
      {
        "name": "db6b09bd-c02a-4d3f-9c9e-f7b697c36347",
        "fromColumn": "Fecha Libro",
        "fromTable": "Agristat live_mm_fact",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_ffcf9b00-c533-40ee-ad42-a445f492ded8"
      },
      {
        "name": "0e8c1d1a-9d3b-4726-b6c1-bca2d1b729ba",
        "fromColumn": "Cruce Maestra Vivo",
        "fromTable": "Agristat live_mm_fact",
        "toColumn": "Cruce Maestra Vivo",
        "toTable": "Maestra Vivo"
      },
      {
        "name": "75666f1f-9821-4972-8e31-6a8a013d8dc6",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Periodo Dólar",
        "fromTable": "Dólar Banco central",
        "toColumn": "Fecha Libro",
        "toTable": "Agristat dim_mm_tm"
      },
      {
        "name": "325147df-dd6a-49a1-996d-ce5df1736e46",
        "fromColumn": "last_db_updt_ts",
        "fromTable": "Agristat lot_mult_mm_fact",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_1159a0d0-a5d5-4120-beae-43967ef541ef"
      },
      {
        "name": "8720355f-23f6-47a2-8cae-3f0e5bbeafae",
        "fromColumn": "clmn_id",
        "fromTable": "Agristat lot_mult_mm_fact",
        "toColumn": "clmn_id",
        "toTable": "Agristat dim_clmn"
      },
      {
        "name": "fa4339d4-b570-4800-b5e3-e182b8fa369d",
        "fromColumn": "run_grp_id",
        "fromTable": "Agristat lot_mult_mm_fact",
        "isActive": false,
        "toColumn": "run_grp_id",
        "toTable": "Agristat dim_run_group"
      },
      {
        "name": "69af2880-504f-4a18-965e-ba452fbf2b98",
        "fromColumn": "Fecha Libro - 6 Meses",
        "fromTable": "Agristat live_mm_fact",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_5206c8d1-fae5-46d0-97a0-f8e6aa8331a8"
      },
      {
        "name": "c0023206-4460-4d6c-92e5-1f381169cbc6",
        "fromColumn": "last_db_updt_ts",
        "fromTable": "Agristat live_mm_fact AGROSUPER AA",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a3902b18-2e54-4675-9228-ed0df837ebf8"
      },
      {
        "name": "c296cb80-5a91-472b-95aa-f36f1f4c28cf",
        "fromColumn": "Periodo Dólar AA",
        "fromTable": "Dólar Banco central AA",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_7270bf4c-a9ee-4fa3-9bac-ec22171551da"
      },
      {
        "name": "2e7ef3bb-e14a-4fd0-82df-c30c7adf071f",
        "fromColumn": "Periodo Dólar AA",
        "fromTable": "Dólar Banco central AA 2017 - 2020",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_fc00b6af-6425-4eaa-80ff-02b5a458d05b"
      },
      {
        "name": "c09ac20d-464b-4ccc-8360-c896d759fcc8",
        "fromColumn": "Cruce Maestra Industrial",
        "fromTable": "Agristat live_mm_fact",
        "toColumn": "Cruce Maestra Industrial",
        "toTable": "Maestra Industrial"
      },
      {
        "name": "19062067-309e-4b9f-91cc-ec536fdff8b0",
        "fromColumn": "Indice",
        "fromTable": "Maestra Industrial",
        "toColumn": "Indice",
        "toTable": "OrdenIndice"
      },
      {
        "name": "3ac88a7e-4bb0-446a-af90-775024f884b8",
        "fromColumn": "Cod. Indice",
        "fromTable": "Agristat live_mm_fact",
        "toColumn": "Cod. Indice",
        "toTable": "Indice Industrial Pollo"
      },
      {
        "name": "ec8c6e70-8b6f-42ce-a4c1-6ff32cc85fc9",
        "fromColumn": "Indice Industrial Pollo",
        "fromTable": "Agristat live_mm_fact",
        "toColumn": "Indice",
        "toTable": "Orden Indice AA"
      },
      {
        "name": "d0b8a670-0994-4582-8374-39332920c6c4",
        "fromColumn": "Cod. Indice",
        "fromTable": "Agristat live_mm_fact",
        "toColumn": "Cod. Indice",
        "toTable": "Indice Industrial Cerdo"
      },
      {
        "name": "94512705-7479-4b89-9e97-b751bd7c41ec",
        "fromColumn": "Indice Industrial Cerdo",
        "fromTable": "Agristat live_mm_fact",
        "toColumn": "Indice",
        "toTable": "Orden Indice AA CERDO"
      }
    ],
    "sourceQueryCulture": "es-CL",
    "tables": [
      {
        "name": "Agristat dim_clmn",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "clmn_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f6707e3f-113d-4b9c-a84f-f57f9d6295cb",
            "sourceColumn": "clmn_id",
            "summarizeBy": "none"
          },
          {
            "name": "clmn_bsn_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e5826ea-c140-4333-aa92-b7e07a81441d",
            "sourceColumn": "clmn_bsn_nm",
            "summarizeBy": "none"
          },
          {
            "name": "Apertura Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e4f9414-2037-4858-b9d8-47bf8ffa5a35",
            "sourceColumn": "Apertura Indice",
            "summarizeBy": "none"
          },
          {
            "name": "clmn_prt_ordr_nbr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "136f1af2-0423-45ea-adae-63ab142477cd",
            "sourceColumn": "clmn_prt_ordr_nbr",
            "summarizeBy": "none"
          },
          {
            "name": "clmn_rpt_file_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4f094676-9524-4ac4-be92-fc9c851a3ff3",
            "sourceColumn": "clmn_rpt_file_cd",
            "summarizeBy": "none"
          },
          {
            "name": "nbr_mask",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dee5ad82-a6ff-4cb0-95be-bbc353dd8332",
            "sourceColumn": "nbr_mask",
            "summarizeBy": "none"
          },
          {
            "name": "lgcy_rpt_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1f2933cc-77cf-4fa9-a6d7-524b476733d5",
            "sourceColumn": "lgcy_rpt_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5fed81bf-3aae-4db2-8f98-f6da0c9a3b5b",
        "partitions": [
          {
            "name": "Agristat dim_clmn-2e9967e9-cc06-4ae0-a464-5cbcd38b3022",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Sql.Database(\"10.195.4.4\", \"sqldb-as-gplanificacionygestion-pyg-prd\"),",
                "    Agristat_dim_clmn = Origen{[Schema=\"Agristat\",Item=\"dim_clmn\"]}[Data],",
                "    #\"Columnas con nombre cambiado\" = Table.RenameColumns(Agristat_dim_clmn,{{\"clmn_rpt_hdng_cd\", \"Apertura Indice\"}})",
                "in",
                "    #\"Columnas con nombre cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_09e3abb8-4beb-43ee-9ce4-7f7a244e1045",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "295a9c37-b647-455e-b2f9-886652088b5f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b097da73-fc09-46b2-bfd3-bdcd02cdc06e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "fcde363f-cff5-4f6e-ad6a-0fb917a5c9e2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "65a2bb00-8d3e-463c-b62e-0ddee947042b",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c37a773c-d2a8-46cc-a0f7-1a46266de347",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2e115ff4-fcfc-4121-8b8c-1b64d06d1e55",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b6a3d101-1a4e-45c9-953f-0b1acd990028",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "0d852d19-83f4-4dd1-8a03-4b6d695f70d9",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "a8a01f96-0573-4633-a7d5-bcb976385c6f",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "04852c9f-93ab-4de5-912e-c3d295584d10",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "08ec6933-1707-4ddc-bca5-05055e4d35c9",
                "ordinal": 3
              }
            ],
            "lineageTag": "6198e3d6-f596-4627-8c2c-175e02a6eab8"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "cecb6050-f834-4b7c-85e2-0212779b88f4",
        "partitions": [
          {
            "name": "DateTableTemplate_09e3abb8-4beb-43ee-9ce4-7f7a244e1045-78535f11-34f7-4848-a5fe-43e5f746a5a7",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Agristat dim_mm_tm",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "mm_tm_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f18ddaf2-8f9c-4a50-8683-75f49467d086",
            "sourceColumn": "mm_tm_id",
            "summarizeBy": "none"
          },
          {
            "name": "cal_mm_nbr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "93e67777-2360-48c6-8296-df40161f70e3",
            "sourceColumn": "cal_mm_nbr",
            "summarizeBy": "none"
          },
          {
            "name": "cal_qtr_nbr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a0952b11-c118-4f50-a9ac-7162b903ab67",
            "sourceColumn": "cal_qtr_nbr",
            "summarizeBy": "none"
          },
          {
            "name": "acct_qtr_nbr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "25945af4-af1f-43cf-8b05-d0df947b9710",
            "sourceColumn": "acct_qtr_nbr",
            "summarizeBy": "none"
          },
          {
            "name": "mm_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1121f342-506b-46e2-b218-65ec1cbac7c8",
            "sourceColumn": "mm_nm",
            "summarizeBy": "none"
          },
          {
            "name": "cal_ccyy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "adef7222-5dc9-4061-a1a4-9f24c494f845",
            "sourceColumn": "cal_ccyy",
            "summarizeBy": "none"
          },
          {
            "name": "cal_ccyy_mm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8f862697-0da2-4710-97a3-c16d99b0e74f",
            "sourceColumn": "cal_ccyy_mm",
            "summarizeBy": "none"
          },
          {
            "name": "cal_ccyy_qtr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb524ac3-d47c-4712-a2ff-a6c259f40fa7",
            "sourceColumn": "cal_ccyy_qtr",
            "summarizeBy": "none"
          },
          {
            "name": "Fecha Libro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mmm\"-\"yy",
            "lineageTag": "53706a19-eff0-4c69-b2e6-83f1abd59e80",
            "sourceColumn": "Fecha Libro",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variación",
                "defaultHierarchy": {
                  "hierarchy": "Jerarquía de fechas",
                  "table": "LocalDateTable_a416ded6-dca5-4204-8c9f-c9f8737ed22c"
                },
                "isDefault": true,
                "relationship": "b8643cd9-5492-4a6d-b679-a3e05d995e5f"
              }
            ]
          },
          {
            "name": "last_db_updt_ts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "ada4d8d9-0e1b-4020-9b2c-e6dda4e8e209",
            "sourceColumn": "last_db_updt_ts",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variación",
                "defaultHierarchy": {
                  "hierarchy": "Jerarquía de fechas",
                  "table": "LocalDateTable_9fd41813-3cbb-41be-900d-e8f01ff89716"
                },
                "isDefault": true,
                "relationship": "76df0829-de47-4ba1-8975-be4f67c3b574"
              }
            ]
          },
          {
            "name": "Columna",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ],
            "dataType": "int64",
            "isDataTypeInferred": true,
            "lineageTag": "33b1bc90-26e6-4c31-a735-e6dd04a2960b",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "3ca4b595-438b-4824-836d-28a97cc9e6e7",
        "partitions": [
          {
            "name": "Agristat dim_mm_tm-52eb1461-9823-46ba-b631-7f90d33586d2",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Sql.Database(\"10.195.4.4\", \"sqldb-as-gplanificacionygestion-pyg-prd\"),",
                "    Agristat_dim_mm_tm = Origen{[Schema=\"Agristat\",Item=\"dim_mm_tm\"]}[Data],",
                "    #\"Columnas con nombre cambiado\" = Table.RenameColumns(Agristat_dim_mm_tm,{{\"cal_dt\", \"Fecha Libro\"}})",
                "in",
                "    #\"Columnas con nombre cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_a416ded6-dca5-4204-8c9f-c9f8737ed22c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3e0faea6-ee55-4d38-b46f-e542cf3ae808",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "569f723e-4f63-493d-9798-f10dbbce8473",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "886e8188-9166-423e-a93c-5d4c2c45024c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "81277567-720c-49bb-a8e6-f428b51ca6c6",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "42fb251a-c0d3-4e89-8d50-2486d9bff51b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "809aadcc-a9dd-419e-8dcc-e1aa6b90b3ef",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5c4d01a9-0e35-4fa1-a60d-51ecb6e2848b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "bb8b8a9c-e830-4d33-b1a8-cf913d4625ee",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "9409d052-6019-4148-900e-b90ead0b9472",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "97e84264-5d69-48d1-8c32-e970704bc91e",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "b08eaea9-6562-4929-9cce-88dba7c5e792",
                "ordinal": 3
              }
            ],
            "lineageTag": "281a9197-c829-4203-848e-e3ab3c67cc10"
          }
        ],
        "isHidden": true,
        "lineageTag": "988e0570-b38e-4a14-bc39-df4439ef1bbc",
        "partitions": [
          {
            "name": "LocalDateTable_a416ded6-dca5-4204-8c9f-c9f8737ed22c-0cd395e6-b1db-4306-a2d5-1ae948e35289",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Agristat dim_mm_tm'[Fecha Libro])), 1, 1), Date(Year(MAX('Agristat dim_mm_tm'[Fecha Libro])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_9fd41813-3cbb-41be-900d-e8f01ff89716",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6ec50436-5002-43d6-99a3-18f4a8f7a2fc",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4b0e1f2d-030e-445b-bce6-d7e37740f84e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "aa200255-cf1e-4352-8bfa-419728c0d4d1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8f1ee201-9e23-4410-a7b3-44234b27bfc5",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "cc33b667-16bc-426a-b2e9-fa02990e91c7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2aa68cb2-db02-43a3-86c9-fc12acc6d622",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3499d2c7-b945-4480-8314-6f916ef7fde5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "889f098b-d869-47ab-a5c7-e53b68a25a87",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "9a48f875-8d2a-4572-b01a-c0208258ad8d",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "f928cdd2-08b3-46f8-8a3a-659fd7afa2fb",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "99eac3ba-17c4-4d77-9a8f-1ab950ae7601",
                "ordinal": 3
              }
            ],
            "lineageTag": "3cfdce3e-2374-423c-a204-fa0541a4b92a"
          }
        ],
        "isHidden": true,
        "lineageTag": "b5ca9c56-c75b-445f-a2b3-0de4719f37bc",
        "partitions": [
          {
            "name": "LocalDateTable_9fd41813-3cbb-41be-900d-e8f01ff89716-fd83e5de-7b56-4023-aaa4-292e9c47afa0",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Agristat dim_mm_tm'[last_db_updt_ts])), 1, 1), Date(Year(MAX('Agristat dim_mm_tm'[last_db_updt_ts])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Agristat dim_run_group",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "run_grp_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "21fb92ee-590e-4160-b9e1-74cae88fdf08",
            "sourceColumn": "run_grp_id",
            "summarizeBy": "none"
          },
          {
            "name": "run_grp_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dbc97a0f-0aad-43a2-a603-56c1982e6651",
            "sourceColumn": "run_grp_cd",
            "summarizeBy": "none"
          },
          {
            "name": "run_grp_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "260208f4-a8fb-43f9-b472-9388c60c31cf",
            "sourceColumn": "run_grp_nm",
            "summarizeBy": "none"
          },
          {
            "name": "run_grp_dsc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6ab3a8c-f824-4f5b-9196-964a7caf21f0",
            "sourceColumn": "run_grp_dsc",
            "summarizeBy": "none"
          },
          {
            "name": "last_db_updt_ts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "56805043-d818-4684-985a-6b886f213c4b",
            "sourceColumn": "last_db_updt_ts",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variación",
                "defaultHierarchy": {
                  "hierarchy": "Jerarquía de fechas",
                  "table": "LocalDateTable_64526ce3-9f69-4e05-a1ae-ee3a71915ef9"
                },
                "isDefault": true,
                "relationship": "6e6840b5-df89-4e54-ae56-939431f2f151"
              }
            ]
          }
        ],
        "lineageTag": "668d997e-075c-4ea9-9df8-cfe0286b509e",
        "partitions": [
          {
            "name": "Agristat dim_run_group-2bf36fdd-f974-4617-8492-dd3f00967cfb",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Sql.Database(\"10.195.4.4\", \"sqldb-as-gplanificacionygestion-pyg-prd\"),",
                "    Agristat_dim_run_group = Origen{[Schema=\"Agristat\",Item=\"dim_run_group\"]}[Data]",
                "in",
                "    Agristat_dim_run_group"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_64526ce3-9f69-4e05-a1ae-ee3a71915ef9",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f31345c0-fe11-433e-bd57-5e2b8b409882",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "72a6b7f1-0c84-4a5e-95fa-b396f022c6fd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ac17e45f-a3c1-46fb-8afc-0db11eedc063",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b42736d8-9858-4a93-b790-62fff721eebb",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f8e75d4f-a6c1-4baf-bc29-2d0eb640bff8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "da13fc77-b36b-463e-b6ff-4b57b37b1eda",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "80c97bcc-1aba-4d7a-947a-781371905452",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "2dc3123c-e103-4a17-bcb4-46c5429f1799",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "1a3ff5eb-332f-40ce-8734-a615bba12aa7",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "97c5b13e-a79c-4188-a1c4-ba9f8af098fa",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "e33364bb-dab8-469a-9ec1-976c25a79527",
                "ordinal": 3
              }
            ],
            "lineageTag": "274123ca-b288-4bf3-b63d-49d59a9a587f"
          }
        ],
        "isHidden": true,
        "lineageTag": "1233decf-618b-48f1-a3fe-89dd179c62f9",
        "partitions": [
          {
            "name": "LocalDateTable_64526ce3-9f69-4e05-a1ae-ee3a71915ef9-27ac4ddf-383f-49fb-ae25-eea98ef2ac23",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Agristat dim_run_group'[last_db_updt_ts])), 1, 1), Date(Year(MAX('Agristat dim_run_group'[last_db_updt_ts])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Agristat lgcy_report",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "lgcy_rpt_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8b9a75d8-0a11-4a80-aa32-644d4d401e44",
            "sourceColumn": "lgcy_rpt_id",
            "summarizeBy": "none"
          },
          {
            "name": "ctry_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f38c2adf-1082-43a7-bea6-1a3908ba7395",
            "sourceColumn": "ctry_cd",
            "summarizeBy": "none"
          },
          {
            "name": "Moneda",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cb833b56-aa31-432a-a5bb-fdeeccbde375",
            "sourceColumn": "Moneda",
            "summarizeBy": "none"
          },
          {
            "name": "sys_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eecd2b88-54d0-401d-bed4-b78d2eda8b23",
            "sourceColumn": "sys_cd",
            "summarizeBy": "none"
          },
          {
            "name": "sys_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c62db3d2-1579-4de0-ac9a-8a602165091b",
            "sourceColumn": "sys_nm",
            "summarizeBy": "none"
          },
          {
            "name": "sctn_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b2fd1341-119c-4030-ba21-240215f3e2f9",
            "sourceColumn": "sctn_cd",
            "summarizeBy": "none"
          },
          {
            "name": "sctn_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "49b779d7-a0c8-4ed0-a726-72613b361216",
            "sourceColumn": "sctn_nm",
            "summarizeBy": "none"
          },
          {
            "name": "sctn_prt_ordr_nbr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2e1f73f0-72ad-44f4-8aca-b3bd3464d3b7",
            "sourceColumn": "sctn_prt_ordr_nbr",
            "summarizeBy": "none"
          },
          {
            "name": "N° Libro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "38d1357a-55a4-4bb8-ad8e-2dc5753a2e9b",
            "sourceColumn": "N° Libro",
            "summarizeBy": "none"
          },
          {
            "name": "rpt_nbr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f9ce826-9199-4bc0-b6a7-cc92e52f8150",
            "sourceColumn": "rpt_nbr",
            "summarizeBy": "none"
          },
          {
            "name": "Descripción N° Libro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "30a377b9-94b5-4161-bcc7-2f07745414de",
            "sourceColumn": "Descripción N° Libro",
            "summarizeBy": "none"
          },
          {
            "name": "rpt_prt_ordr_nbr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d508ab40-8c4c-4682-b516-ea6c28850fd6",
            "sourceColumn": "rpt_prt_ordr_nbr",
            "summarizeBy": "none"
          },
          {
            "name": "last_db_updt_ts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "e565559f-a17e-4337-a0e0-3e3f777bb6b7",
            "sourceColumn": "last_db_updt_ts",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variación",
                "defaultHierarchy": {
                  "hierarchy": "Jerarquía de fechas",
                  "table": "LocalDateTable_90bf2604-53f0-4c0d-b9b0-d1c91892761d"
                },
                "isDefault": true,
                "relationship": "36b7aab5-7328-4108-92d1-0ec7785f61da"
              }
            ]
          },
          {
            "name": "lgcy_sprog_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f0b059d9-9014-4037-a048-4a0a3ca05a79",
            "sourceColumn": "lgcy_sprog_id",
            "summarizeBy": "none"
          },
          {
            "name": "Moneda Desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IFERROR(IF('Agristat lgcy_report'[ctry_cd]=\"5\", \"USD\",\"CLP\"),\"\")",
            "isDataTypeInferred": true,
            "lineageTag": "3ce7cb2b-74aa-471f-a787-197a12c18b12",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "06124bb1-b5f7-4ee7-b74b-d0f8cd7e8bb8",
        "partitions": [
          {
            "name": "Agristat lgcy_report-d9e14f51-bc51-4445-ba36-164dbbe1ed5d",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Sql.Database(\"10.195.4.4\", \"sqldb-as-gplanificacionygestion-pyg-prd\"),",
                "    Agristat_lgcy_report = Origen{[Schema=\"Agristat\",Item=\"lgcy_report\"]}[Data],",
                "    #\"Columnas con nombre cambiado\" = Table.RenameColumns(Agristat_lgcy_report,{{\"ctry_nm\", \"Moneda\"}, {\"rpt_cd\", \"N° Libro\"}, {\"rpt_nm\", \"Descripción N° Libro\"}})",
                "in",
                "    #\"Columnas con nombre cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_90bf2604-53f0-4c0d-b9b0-d1c91892761d",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7f7cd4dc-2b01-4580-a077-6f26d5d67626",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2179c616-8abe-4954-a9be-55d143161dcc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9075dbd1-9bfd-4656-9137-a01c79087173",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9ad5fb52-75bf-447d-ae70-d00170e45e0d",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f50d407d-b49d-4269-88a4-94d86e1a6b2d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "88180f9c-d1b2-4ca7-ad52-85881f94fc44",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5e00d10c-b314-408e-bec1-5fb2f2744893",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "526d43bb-55ec-4b04-9bf6-3502027c50f6",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "5c9bd393-8d26-4daa-8a1f-e437d6c86570",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "a7854c88-878e-425d-a360-adcca3fb061c",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "1edaa3bb-f37a-4f7f-86a2-5a24e8ee4479",
                "ordinal": 3
              }
            ],
            "lineageTag": "5306da71-d2f8-4d6a-92e4-00e3fcfbcd24"
          }
        ],
        "isHidden": true,
        "lineageTag": "556587b9-08c3-4fd0-90d5-f263055123e3",
        "partitions": [
          {
            "name": "LocalDateTable_90bf2604-53f0-4c0d-b9b0-d1c91892761d-4817c9d6-33e8-4b31-9065-c886ca62faf4",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Agristat lgcy_report'[last_db_updt_ts])), 1, 1), Date(Year(MAX('Agristat lgcy_report'[last_db_updt_ts])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Agristat lgcy_sprog",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "lgcy_sprog_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "17ef5ed6-77f4-4a72-b0fe-122ef8da82f8",
            "sourceColumn": "lgcy_sprog_id",
            "summarizeBy": "none"
          },
          {
            "name": "prog_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e58fc541-f9c2-493a-8166-7315e0301047",
            "sourceColumn": "prog_cd",
            "summarizeBy": "none"
          },
          {
            "name": "Sector",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e351aa62-81ed-4a6a-8694-9f3925a4c73b",
            "sourceColumn": "Sector",
            "summarizeBy": "none"
          },
          {
            "name": "sprog_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "186ee596-1d91-4f09-9f6f-c9b1b69fcde4",
            "sourceColumn": "sprog_cd",
            "summarizeBy": "none"
          },
          {
            "name": "sprog_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "349877b8-abe2-4fa4-8b5e-84658218e4a1",
            "sourceColumn": "sprog_nm",
            "summarizeBy": "none"
          },
          {
            "name": "last_db_updt_ts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "2e9a616b-28b2-42f1-8e7b-bbabc5e40a42",
            "sourceColumn": "last_db_updt_ts",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variación",
                "defaultHierarchy": {
                  "hierarchy": "Jerarquía de fechas",
                  "table": "LocalDateTable_a917c58e-4e9b-4816-8090-23d8ac4cd422"
                },
                "isDefault": true,
                "relationship": "975af22b-f76a-4c77-bbd4-9a02e86c155e"
              }
            ]
          }
        ],
        "lineageTag": "2b7d7620-0622-4346-96e0-1297243368f0",
        "partitions": [
          {
            "name": "Agristat lgcy_sprog-abb66514-a702-473e-89bd-0bbae5ee135f",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Sql.Database(\"10.195.4.4\", \"sqldb-as-gplanificacionygestion-pyg-prd\"),",
                "    Agristat_lgcy_sprog = Origen{[Schema=\"Agristat\",Item=\"lgcy_sprog\"]}[Data],",
                "    #\"Columnas con nombre cambiado\" = Table.RenameColumns(Agristat_lgcy_sprog,{{\"prog_nm\", \"Sector\"}})",
                "in",
                "    #\"Columnas con nombre cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_a917c58e-4e9b-4816-8090-23d8ac4cd422",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "8ef26659-6aee-4bd9-9b63-cc34920140c4",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "79b1182d-4ada-4e8e-919f-43795e2bdc2a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "cfb3363d-d012-4c07-b8f5-5f0da312573a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c39ddb28-6ac9-4c82-a044-11a366467ee7",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7e9e004f-3850-4f66-aebe-4c2961090e05",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0394a1e2-dc97-4628-9063-19f708f44655",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d66623f3-06e6-4bf6-9268-c05f8d1d84e7",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "e77db42c-e9d8-4aeb-9644-9934cea31f9c",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "52d35c67-7b35-401c-8961-2eb3167bbdea",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "126c9320-cf36-4017-b4e9-fbda53534919",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "6dff6c41-b786-419d-8256-ad46728c303b",
                "ordinal": 3
              }
            ],
            "lineageTag": "5eaacf78-09b4-4d8d-add8-f864f68ab49f"
          }
        ],
        "isHidden": true,
        "lineageTag": "dc5c2940-f645-4e1a-9047-e87b02806a03",
        "partitions": [
          {
            "name": "LocalDateTable_a917c58e-4e9b-4816-8090-23d8ac4cd422-b1f5f6cd-31fc-496b-9122-3275e9b65058",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Agristat lgcy_sprog'[last_db_updt_ts])), 1, 1), Date(Year(MAX('Agristat lgcy_sprog'[last_db_updt_ts])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Agristat live_mm_fact",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "live_mm_fact_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DataType"
              }
            ],
            "dataType": "double",
            "formatString": "#,0",
            "lineageTag": "cf23df39-a8ee-4c8c-b7e7-fd7045740cc6",
            "sourceColumn": "live_mm_fact_id",
            "summarizeBy": "sum"
          },
          {
            "name": "mm_tm_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "73377ce2-1909-49da-9e8c-4afbaaefa06e",
            "sourceColumn": "mm_tm_id",
            "summarizeBy": "none"
          },
          {
            "name": "run_grp_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "1e27e58c-37ea-4818-bad4-4e0bdaa829ea",
            "sourceColumn": "run_grp_id",
            "summarizeBy": "none"
          },
          {
            "name": "clmn_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "370bc1fe-ccca-43ba-8efc-c3e06db535bc",
            "sourceColumn": "clmn_id",
            "summarizeBy": "none"
          },
          {
            "name": "line_grp_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e87388cc-1919-4896-bfb9-2dcde01d76e5",
            "sourceColumn": "line_grp_cd",
            "summarizeBy": "none"
          },
          {
            "name": "Cod. Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6ef80e2-25ce-4c24-83c2-6e2551190011",
            "sourceColumn": "Cod. Indice",
            "summarizeBy": "none"
          },
          {
            "name": "Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d989c944-c89e-490e-84aa-60f28082e14f",
            "sourceColumn": "Indice",
            "summarizeBy": "none"
          },
          {
            "name": "nmrc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "20cf68a1-4e67-4ec4-b09c-a5a04b1a0140",
            "sourceColumn": "nmrc",
            "summarizeBy": "sum"
          },
          {
            "name": "charval",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a57c4839-c8a7-4ad2-954c-5b42aa18391b",
            "sourceColumn": "charval",
            "summarizeBy": "none"
          },
          {
            "name": "last_db_updt_ts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "7405ca64-680b-47db-9c26-a2793680faba",
            "sourceColumn": "last_db_updt_ts",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variación",
                "defaultHierarchy": {
                  "hierarchy": "Jerarquía de fechas",
                  "table": "LocalDateTable_67a10a6a-6e8d-4348-aef2-26425e82f0be"
                },
                "isDefault": true,
                "relationship": "433c51e5-c5c7-427d-9ac5-251536a2338a"
              }
            ]
          },
          {
            "name": "fact_type_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "55d28d99-f90d-48e1-a3c9-15293454ea4f",
            "sourceColumn": "fact_type_cd",
            "summarizeBy": "none"
          },
          {
            "name": "N Libro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "RELATED('Agristat lgcy_report'[N° Libro])",
            "isDataTypeInferred": true,
            "lineageTag": "2dae145c-b39e-49ae-adc6-58cc089df8a7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Apertura Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "RELATED('Agristat dim_clmn'[Apertura Indice])",
            "isDataTypeInferred": true,
            "lineageTag": "1e36f37c-3ddc-4923-950e-8a3e31794c39",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Cruce Maestra",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "'Agristat live_mm_fact'[N Libro]&'Agristat live_mm_fact'[Apertura Indice]&'Agristat live_mm_fact'[Indice]",
            "isDataTypeInferred": true,
            "lineageTag": "2859e242-7129-454d-9977-48d714dd256a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Fecha Libro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "expression": "RELATED('Agristat dim_mm_tm'[Fecha Libro])",
            "formatString": "mmm\"-\"yy",
            "isDataTypeInferred": true,
            "lineageTag": "1a62edc1-ac8c-42e8-9664-ade0a6090a27",
            "summarizeBy": "none",
            "type": "calculated",
            "variations": [
              {
                "name": "Variación",
                "defaultHierarchy": {
                  "hierarchy": "Jerarquía de fechas",
                  "table": "LocalDateTable_ffcf9b00-c533-40ee-ad42-a445f492ded8"
                },
                "isDefault": true,
                "relationship": "db6b09bd-c02a-4d3f-9c9e-f7b697c36347"
              }
            ]
          },
          {
            "name": "Actualización",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "\"Información desde \"&UPPER(FORMAT(MIN('Agristat live_mm_fact'[Fecha Libro]),\"mmm\"))&\"-\"&FORMAT(MIN('Agristat live_mm_fact'[Fecha Libro]),\"YYYY\")&\" a \"&UPPER(FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"mmm\"))&\"-\"&MAX('Agristat live_mm_fact'[Fecha Libro].[Año])",
            "isDataTypeInferred": true,
            "lineageTag": "133c671a-f1d7-4434-b77b-1d799c39af89",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Cruce Maestra Vivo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "'Agristat live_mm_fact'[Sector]&'Agristat live_mm_fact'[N Libro]&'Agristat live_mm_fact'[Cod. Indice]&'Agristat live_mm_fact'[Apertura Indice]",
            "isDataTypeInferred": true,
            "lineageTag": "0c2e3556-9a89-42da-a323-05ac28557097",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dólar",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "string",
            "expression": "RELATED('Dólar Banco central'[Dólar])",
            "isDataTypeInferred": true,
            "lineageTag": "bd6aabb9-0959-436a-8160-e415b73ee6a9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "nmrc clp para usd en 0",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "CALCULATE(",
              "\tSUM('Agristat live_mm_fact'[nmrc]),'Agristat live_mm_fact'[Moneda]=\"CLP\",",
              "\tALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[mm_tm_id],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Sector])",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "d3a0715a-15e5-49ca-897a-c4099de730b3",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Moneda",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "RELATED('Agristat lgcy_report'[Moneda Desc])",
            "isDataTypeInferred": true,
            "lineageTag": "f03aa2bc-d9ac-43f1-bcd3-61a2071a0d99",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NMRC clp a USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "            IF('Agristat live_mm_fact'[Moneda]=\"USD\" && ",
              "                'Agristat live_mm_fact'[Sector]=\"SWINE\" && ",
              "                'Agristat live_mm_fact'[sys_cd]=\"SWINE\" && ",
              "                NOT 'Agristat live_mm_fact'[nmrc]='Agristat live_mm_fact'[nmrc clp para usd en 0] && ",
              "                ('Agristat live_mm_fact'[Indice]=\"AGROSUPER AA\" || 'Agristat live_mm_fact'[Indice]=\"AGROSUPER S.A. AA\"),",
              "                    'Agristat live_mm_fact'[nmrc clp para usd en 0]/'Agristat live_mm_fact'[Dólar AA],",
              "                        IF('Agristat live_mm_fact'[Moneda]=\"USD\" && ",
              "                            'Agristat live_mm_fact'[Sector]=\"SWINE\" && ",
              "                            'Agristat live_mm_fact'[sys_cd]=\"SWINE\" && ",
              "                            NOT 'Agristat live_mm_fact'[nmrc]='Agristat live_mm_fact'[nmrc clp para usd en 0],",
              "                            'Agristat live_mm_fact'[nmrc clp para usd en 0]/'Agristat live_mm_fact'[Dólar],",
              "                                IF('Agristat live_mm_fact'[Moneda]=\"USD\" && ",
              "                                    ('Agristat live_mm_fact'[Sector]=\"SWINE\" || 'Agristat live_mm_fact'[Sector]=\"BROILER\") && ",
              "                                    ('Agristat live_mm_fact'[sys_cd]=\"SWPRO\" || 'Agristat live_mm_fact'[sys_cd]=\"PROCE\") && ",
              "                                    NOT 'Agristat live_mm_fact'[nmrc]='Agristat live_mm_fact'[nmrc clp para usd en 0] && ",
              "                                    ('Agristat live_mm_fact'[Indice]=\"AGROSUPER AA\" || 'Agristat live_mm_fact'[Indice]=\"AGROSUPER S.A. AA\"),",
              "                                        ('Agristat live_mm_fact'[nmrc clp para usd en 0]/'Agristat live_mm_fact'[Dólar AA])*100,",
              "                                            IF('Agristat live_mm_fact'[Moneda]=\"USD\" && ",
              "                                            ('Agristat live_mm_fact'[Sector]=\"SWINE\" || 'Agristat live_mm_fact'[Sector]=\"BROILER\") && ",
              "                                            ('Agristat live_mm_fact'[sys_cd]=\"SWPRO\" || 'Agristat live_mm_fact'[sys_cd]=\"PROCE\") && ",
              "                                            NOT 'Agristat live_mm_fact'[nmrc]='Agristat live_mm_fact'[nmrc clp para usd en 0],",
              "                                                ('Agristat live_mm_fact'[nmrc clp para usd en 0]/'Agristat live_mm_fact'[Dólar])*100,",
              "                                                'Agristat live_mm_fact'[nmrc]",
              "                                            )",
              "                                )",
              "                        )",
              "            )"
            ],
            "formatString": "#,0.00",
            "isDataTypeInferred": true,
            "lineageTag": "35108205-e49d-4945-bfc9-975bc92fd497",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Sector",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "RELATED('Agristat lgcy_sprog'[Sector])",
            "isDataTypeInferred": true,
            "lineageTag": "6c428169-2cb2-4739-9709-4059c3bca90e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "sys_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "RELATED('Agristat lgcy_report'[sys_cd])",
            "isDataTypeInferred": true,
            "lineageTag": "98e43095-b37e-4963-adc1-c9de4b88afd8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Fecha Libro - 6 Meses",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "expression": "DATEADD('Agristat live_mm_fact'[Fecha Libro],-6,MONTH)",
            "formatString": "mmmm \"de\" yyyy",
            "isDataTypeInferred": true,
            "lineageTag": "ba5cf427-713d-43b5-9b6a-e7e95dfb3b51",
            "summarizeBy": "none",
            "type": "calculated",
            "variations": [
              {
                "name": "Variación",
                "defaultHierarchy": {
                  "hierarchy": "Jerarquía de fechas",
                  "table": "LocalDateTable_5206c8d1-fae5-46d0-97a0-f8e6aa8331a8"
                },
                "isDefault": true,
                "relationship": "69af2880-504f-4a18-965e-ba452fbf2b98"
              }
            ]
          },
          {
            "name": "Desc Apertura Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "RELATED('Agristat dim_clmn'[clmn_bsn_nm])",
            "isDataTypeInferred": true,
            "lineageTag": "5766dccd-bacf-4b66-be6e-0c7f8f758020",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "mm_tm_id.1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dbd94149-cb08-49ab-b2a8-367dc4eea659",
            "sourceColumn": "mm_tm_id.1",
            "summarizeBy": "none"
          },
          {
            "name": "Cod. Indice y Descripción",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "'Agristat live_mm_fact'[N Libro]&\" - \"&'Agristat live_mm_fact'[Apertura Indice]&\" - \"&'Agristat live_mm_fact'[Desc Apertura Indice]",
            "isDataTypeInferred": true,
            "lineageTag": "a16c24b5-e752-456c-aed7-5eab3d94a49f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dólar AA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "string",
            "expression": "RELATED('Dólar Banco central'[Dólar AA])",
            "isDataTypeInferred": true,
            "lineageTag": "54f74a24-d899-4d5d-b0c4-d23580e1a690",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Cruce Maestra Industrial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "'Agristat live_mm_fact'[sys_cd]&'Agristat live_mm_fact'[Sector]&'Agristat live_mm_fact'[N Libro]&'Agristat live_mm_fact'[Apertura Indice]&'Agristat live_mm_fact'[Cod. Indice]",
            "isDataTypeInferred": true,
            "lineageTag": "4bcd06ec-51d0-4e10-9687-34d6f4574154",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Indice Maestra Industrial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "RELATED('Maestra Industrial'[Indice])",
            "isDataTypeInferred": true,
            "lineageTag": "74a2193c-13cf-4d66-95a7-0b2105eb37cc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "nmrc*10 LM y SV",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "IF('Agristat live_mm_fact'[Cod. Indice]=\"0700\" || 'Agristat live_mm_fact'[Cod. Indice]=\"0701\",'Agristat live_mm_fact'[NMRC clp a USD]*10,BLANK())",
            "isDataTypeInferred": true,
            "lineageTag": "6779107e-1525-44d9-aaf0-e59f36e7c0b7",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "nmrc*10 DyT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "IF('Agristat live_mm_fact'[Cod. Indice]=\"SALTY04\",'Agristat live_mm_fact'[NMRC clp a USD]*10,BLANK())",
            "isDataTypeInferred": true,
            "lineageTag": "05d8d97e-b02c-4fe7-bb0d-394da2eb2929",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "nmrc*10 T25",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "IF('Agristat live_mm_fact'[Cod. Indice]=\"A3025\",'Agristat live_mm_fact'[NMRC clp a USD]*10,BLANK())",
            "isDataTypeInferred": true,
            "lineageTag": "f8b5657c-3231-4885-a30c-02912eecf00c",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "nmrc*10 LM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "IF('Agristat live_mm_fact'[Cod. Indice]=\"0700\",'Agristat live_mm_fact'[NMRC clp a USD]*10,BLANK())",
            "isDataTypeInferred": true,
            "lineageTag": "3de4c80c-fa3b-435d-993a-5951ae2b2efd",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "nmrc*10 SV",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "IF('Agristat live_mm_fact'[Cod. Indice]=\"0701\",'Agristat live_mm_fact'[NMRC clp a USD]*10,BLANK())",
            "isDataTypeInferred": true,
            "lineageTag": "b94f2942-0a91-4177-907a-0d2996a231f9",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Indice Industrial Pollo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "IF(RIGHT('Agristat live_mm_fact'[Indice],2)=\"AA\",RELATED('Indice Industrial Pollo'[Indice])&\" AA\",RELATED('Indice Industrial Pollo'[Indice]))",
            "isDataTypeInferred": true,
            "lineageTag": "a7dd2bf7-3971-4457-818b-8f333346b51f",
            "sortByColumn": "Orden Indice",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Orden Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "RELATED('Orden Indice AA'[Orden Indice])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "a8047fa6-d969-4307-9b22-077f4195da6e",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Desc Apertura Indice REEM kg",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "SUBSTITUTE(SUBSTITUTE(SUBSTITUTE('Agristat live_mm_fact'[Desc Apertura Indice],\"Kg\",\"Ton\"),\"KG\",\"Ton\"),\"kg\",\"Ton\")",
            "isDataTypeInferred": true,
            "lineageTag": "1a7d2361-3156-449b-a526-c6257e39115e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Cod. Indice y Descripción INDUSTRIAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "'Agristat live_mm_fact'[N Libro]&\" - \"&'Agristat live_mm_fact'[Apertura Indice]&\" - \"&'Agristat live_mm_fact'[Desc Apertura Indice REEM kg]",
            "isDataTypeInferred": true,
            "lineageTag": "9b834f41-36d7-476a-8747-67f09909a500",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Titulo Tabla Apertura Ultimo mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "\"Detalle Último Mes (\"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"Mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"YYYY\")&\")\"",
            "isDataTypeInferred": true,
            "lineageTag": "562c6b91-19fd-460a-b9e4-af6fb4315369",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Indice Industrial Cerdo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "IF(RIGHT('Agristat live_mm_fact'[Indice],2)=\"AA\",RELATED('Indice Industrial Cerdo'[Indice])&\" AA\",RELATED('Indice Industrial Cerdo'[Indice]))",
            "isDataTypeInferred": true,
            "lineageTag": "6b48fe8c-318b-40e7-b8c7-0979910f9613",
            "sortByColumn": "Orden Indice CERDO",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Orden Indice CERDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "RELATED('Orden Indice AA CERDO'[Orden Indice])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "e3f00515-a754-4372-b4a8-67ca9605fe6b",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "nmrc*10 LM y RS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "IF('Agristat live_mm_fact'[Cod. Indice]=\"6655\" || 'Agristat live_mm_fact'[Cod. Indice]=\"6656\",'Agristat live_mm_fact'[NMRC clp a USD]*10,BLANK())",
            "isDataTypeInferred": true,
            "lineageTag": "8e1ab224-b7fb-4e04-ad96-cc634af50060",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "nmrc*10 T25 Cerdo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "IF('Agristat live_mm_fact'[Cod. Indice]=\"A3125\",'Agristat live_mm_fact'[NMRC clp a USD]*10,BLANK())",
            "isDataTypeInferred": true,
            "lineageTag": "56369416-c92e-44c4-a249-746d82347d8b",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "nmrc*10 PromInd Cerdo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "IF('Agristat live_mm_fact'[Cod. Indice]=\"OG3L\",'Agristat live_mm_fact'[NMRC clp a USD]*10,BLANK())",
            "isDataTypeInferred": true,
            "lineageTag": "d37ba63f-d80c-405c-92a8-31e5ca84e9b2",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "nmrc*10 LM Cerdo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "IF('Agristat live_mm_fact'[Cod. Indice]=\"6655\",'Agristat live_mm_fact'[NMRC clp a USD]*10,BLANK())",
            "isDataTypeInferred": true,
            "lineageTag": "3e74ab05-1d8f-4512-87b4-c5aab3b168d6",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "nmrc*10 RS Cerdo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "IF('Agristat live_mm_fact'[Cod. Indice]=\"6656\",'Agristat live_mm_fact'[NMRC clp a USD]*10,BLANK())",
            "isDataTypeInferred": true,
            "lineageTag": "4ceb62c2-bfa7-4c8d-a8cc-1d27852bbaef",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "nmrc*10 LM Cerdo Fijo Colum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "CALCULATE(SUM('Agristat live_mm_fact'[NMRC clp a USD])*10,FILTER(ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[Fecha Libro],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Desc Apertura Indice REEM kg]),'Agristat live_mm_fact'[Indice Industrial Cerdo]=\"LO MIRANDA\"))",
            "isDataTypeInferred": true,
            "lineageTag": "ff0b2d35-424b-4848-af10-7792fecc4255",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "nmrc*10 RS Cerdo Fijo Colum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "CALCULATE(SUM('Agristat live_mm_fact'[NMRC clp a USD])*10,FILTER(ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[Fecha Libro],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Desc Apertura Indice REEM kg]),'Agristat live_mm_fact'[Indice Industrial Cerdo]=\"ROSARIO\"))",
            "isDataTypeInferred": true,
            "lineageTag": "7bab3aac-c5be-4e0b-ac1c-e2bfdb2c177e",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Desc. N° de Libro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "RELATED('Agristat lgcy_report'[Descripción N° Libro])",
            "isDataTypeInferred": true,
            "lineageTag": "d4d88aad-a930-4a83-9f05-6fa2d3049988",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Indice Prod Animal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "IF('Agristat live_mm_fact'[Cod. Indice]=\"6653\" && 'Agristat live_mm_fact'[Indice]=\"AGROSUPER 1 RANCAGUA, CHILE\",\"LO MIRANDA\",IF('Agristat live_mm_fact'[Cod. Indice]=\"6653\" && 'Agristat live_mm_fact'[Indice]=\"AGROSUPER 1 RANCAGUA, CHILE AA\",\"LO MIRANDA AA\",IF('Agristat live_mm_fact'[Cod. Indice]=\"6654\" && 'Agristat live_mm_fact'[Indice]=\"AGROSUPER 2 RANCAGUA, CHILE\",\"SAN VICENTE\",IF('Agristat live_mm_fact'[Cod. Indice]=\"6654\" && 'Agristat live_mm_fact'[Indice]=\"AGROSUPER 2 RANCAGUA, CHILE AA\",\"SAN VICENTE AA\",'Agristat live_mm_fact'[Indice]))))",
              "",
              "",
              "/*,SUBSTITUTE('Agristat live_mm_fact'[Indice], \"AGROSUPER 1 RANCAGUA, CHILE\", \"Lo Miranda\"),IF('Agristat live_mm_fact'[Cod. Indice]=\"6653\",SUBSTITUTE('Agristat live_mm_fact'[Indice], \"AGROSUPER 1 RANCAGUA, CHILE\", \"Lo Miranda\")",
              "*/"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "575ab121-7653-44f2-a6ec-176eaf4331d1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Indice Prod Animal POLLO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF('Agristat live_mm_fact'[Cod. Indice]=\"0700\",\"LO MIRANDA\",IF('Agristat live_mm_fact'[Cod. Indice]=\"0701\",\"LONGOVILO\",IF('Agristat live_mm_fact'[Cod. Indice]=\"0702\",\"CASA BLANCA\",IF('Agristat live_mm_fact'[Cod. Indice]=\"1790\",\"LA CALERA\",'Agristat live_mm_fact'[Indice]))))",
            "isDataTypeInferred": true,
            "lineageTag": "35409d16-003f-44b1-9b14-84384ea67cd2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Indice Prod Animal POLLO Incubación",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF('Agristat live_mm_fact'[Cod. Indice]=\"0700\",\"ARAÑAS\",IF('Agristat live_mm_fact'[Cod. Indice]=\"0701\",\"MIRANDA 01\",IF('Agristat live_mm_fact'[Cod. Indice]=\"0703\",\"MIRANDA 02\",'Agristat live_mm_fact'[Indice])))",
            "isDataTypeInferred": true,
            "lineageTag": "9eeaaddb-c4a7-4936-826f-d09499c55b43",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "09d25f31-290c-4c08-99c5-971ab7f6cbd1",
        "measures": [
          {
            "name": "nmrc/12",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "SUM('Agristat live_mm_fact'[NMRC clp a USD])/12",
            "formatString": "#,0.00",
            "lineageTag": "3304f33d-759e-4cdb-8c2f-0dac6f96aeea"
          },
          {
            "name": "nmrc*1000",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "SUM('Agristat live_mm_fact'[NMRC clp a USD])*1000",
            "formatString": "#,0",
            "lineageTag": "d1aa265e-a0a0-4d60-a3c4-90d50c8dc017"
          },
          {
            "name": "1-nmrc/1000 Mortalidad %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "IF(SUM('Agristat live_mm_fact'[nmrc])>0,1-(SUM('Agristat live_mm_fact'[nmrc])/100))",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "42f88d07-a5f4-4e7c-b210-f5def947ca4f"
          },
          {
            "name": "nmrc Medida",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "SUM('Agristat live_mm_fact'[NMRC clp a USD])",
            "formatString": "#,0.00",
            "lineageTag": "ef3f5164-6a08-44fd-a2e3-1acfd4c54afc"
          },
          {
            "name": "nmrc/1000",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "SUM('Agristat live_mm_fact'[NMRC clp a USD])/1000",
            "formatString": "#,0.000",
            "lineageTag": "11772009-9b7e-492b-b09b-b204fe96bb2b"
          },
          {
            "name": "nmrc*10",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "SUM('Agristat live_mm_fact'[NMRC clp a USD])*10",
            "formatString": "#,0.00",
            "lineageTag": "d3b60d6a-3a1a-4140-84f8-60c3061619fd"
          },
          {
            "name": "nmrc*100",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "SUM('Agristat live_mm_fact'[NMRC clp a USD])*100",
            "formatString": "#,0.00",
            "lineageTag": "4dd7b6a9-3e17-49a8-82a6-c3d3cc0de66f"
          },
          {
            "name": "nmrc/12*10",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "(SUM('Agristat live_mm_fact'[NMRC clp a USD])/12)*10",
            "formatString": "0.00",
            "lineageTag": "53c04050-9c51-4389-94dc-a746533c4c6c"
          },
          {
            "name": "nmrc*1000 Ult 6 Meses",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 6 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Indice Industrial Pollo]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-165<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 3 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Indice Industrial Pollo]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-85<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 12 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Indice Industrial Pollo]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Mes Anterior\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Indice Industrial Pollo]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-35<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])-5>='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              ")))))"
            ],
            "formatString": "#,0",
            "lineageTag": "350edb2b-4909-4bc2-8d32-a7651c198e3b"
          },
          {
            "name": "nmrc*1000 Ult 6 Meses AGROSUPER",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 6 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-165<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"Agrosuper S.A.\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 3 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-85<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"Agrosuper S.A.\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 12 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"Agrosuper S.A.\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Mes Anterior\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-34<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])-5>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"Agrosuper S.A.\"",
              "        )",
              ")))))"
            ],
            "lineageTag": "4137f27a-23c2-47bc-9030-aba6150b9448"
          },
          {
            "name": "Dif/Agrosuper",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "IF([nmrc*1000 Ult 6 Meses AGROSUPER]-[nmrc*1000 Ult 6 Meses]<=1 && [nmrc*1000 Ult 6 Meses AGROSUPER]-[nmrc*1000 Ult 6 Meses]>=-1,BLANK(),[nmrc*1000 Ult 6 Meses AGROSUPER]-[nmrc*1000 Ult 6 Meses])/1000",
            "formatString": "#,0.00",
            "lineageTag": "acc0cfa3-3f66-4277-9e77-a4b5e4b87091"
          },
          {
            "name": "Dif %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "IF([nmrc*1000 Ult 6 Meses AGROSUPER]-[nmrc*1000 Ult 6 Meses]<=1 && [nmrc*1000 Ult 6 Meses AGROSUPER]-[nmrc*1000 Ult 6 Meses]>=-1,BLANK(),[nmrc*1000 Ult 6 Meses AGROSUPER]/[nmrc*1000 Ult 6 Meses]-1)",
            "formatString": "0.0\\ %;-0.0\\ %;0.0\\ %",
            "lineageTag": "e662c5e3-96cd-4fd9-a5b9-d0d1702062d1"
          },
          {
            "name": "nmrc Ult Mes Q AGROSUPER D.3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(SUM('Agristat live_mm_fact'[nmrc]), ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"Agrosuper S.A.\"",
              "             && 'Agristat live_mm_fact'[Apertura Indice]=\"d.3\"",
              "        )",
              ")"
            ],
            "lineageTag": "6172eff5-4803-4881-bc0a-7e1cdb6b90b8"
          },
          {
            "name": "Dif/mes $ D.3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "IF([nmrc*1000 Ult 6 Meses AGROSUPER]-[nmrc*1000 Ult 6 Meses]<=0.0001 && [nmrc*1000 Ult 6 Meses AGROSUPER]-[nmrc*1000 Ult 6 Meses]>=-0.0001,BLANK(), [nmrc Ult Mes Q AGROSUPER D.3]*[Dif/Agrosuper]/1)",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "14b09d74-4fbf-47ae-83fe-466211c2d311"
          },
          {
            "name": "nmrc Ult 12 Meses Q AGROSUPER D.3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(SUM('Agristat live_mm_fact'[nmrc]), ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"Agrosuper S.A.\" && 'Agristat live_mm_fact'[Apertura Indice]=\"d.3\"",
              "        )",
              ")"
            ],
            "lineageTag": "9c987b11-b05a-4de0-9006-14626b880534"
          },
          {
            "name": "Dif/año $ D.3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "IF([nmrc*1000 Ult 6 Meses AGROSUPER]-[nmrc*1000 Ult 6 Meses]<=0.0001 && [nmrc*1000 Ult 6 Meses AGROSUPER]-[nmrc*1000 Ult 6 Meses]>=-0.0001,BLANK(), [nmrc Ult 12 Meses Q AGROSUPER D.3]*[Dif/Agrosuper] /1)",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "40fab5e5-84d6-4900-9899-74e26ed9635e"
          },
          {
            "name": "Titulo Tabla",
            "expression": [
              "--\"Comparación Promedio \"&SELECTEDVALUE('Filtro Comparación'[Comparación])&\" vs \" &FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"YYYY\")",
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 6 meses\",\"Impacto Económico Promedio \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-145,\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-145,\"YYYY\")&\" a \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"YYYY\"),",
              "",
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 3 meses\",\"Impacto Económico Promedio \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-55,\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-55,\"YYYY\")&\" a \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"YYYY\"),",
              "",
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 12 meses\",\"Impacto Económico Promedio \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-325,\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-325,\"YYYY\")&\" a \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"YYYY\"),",
              "",
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Mes Anterior\",\"Impacto Económico Promedio \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-5,\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-5,\"YYYY\")&\" a \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"YYYY\")",
              "",
              "))))"
            ],
            "lineageTag": "b9a57caf-8c1d-44b8-b632-56be3a31685e"
          },
          {
            "name": "Ult. Meses Cascada",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 6 meses\",CALCULATE((SUM('Agristat live_mm_fact'[NMRC clp a USD]))/6, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-165<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"Agrosuper S.A.\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 3 meses\",CALCULATE((SUM('Agristat live_mm_fact'[NMRC clp a USD]))/3, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-85<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"Agrosuper S.A.\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 12 meses\",CALCULATE((SUM('Agristat live_mm_fact'[NMRC clp a USD]))/12, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"Agrosuper S.A.\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Mes Anterior\",CALCULATE((SUM('Agristat live_mm_fact'[NMRC clp a USD]))/1, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-34<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])-5>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"Agrosuper S.A.\"",
              "        )",
              ")))))"
            ],
            "formatString": "#,0",
            "lineageTag": "7a8f58fb-e55f-4a7b-a11e-9b7b452ffcdb"
          },
          {
            "name": "Ult. Mes Cascada",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "CALCULATE(SUM('Agristat live_mm_fact'[NMRC clp a USD]), ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[Desc Apertura Indice], 'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[sys_cd], 'Agristat live_mm_fact'[Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              ")"
            ],
            "lineageTag": "516ac2de-80d6-4139-a38f-23519d1a953d"
          },
          {
            "name": "Dif Grafico cascada",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Ult. Mes Cascada]-[Ult. Meses Cascada]",
            "lineageTag": "31c7e5e2-4ef8-4b34-8c82-8e875c45f709"
          },
          {
            "name": "Display",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "SWITCH(",
              "                SELECTEDVALUE('Filtro Cascada'[ID]),",
              "                1, [Ult. Meses Cascada],",
              "                2, [Ult. Mes Cascada]",
              ") "
            ],
            "formatString": "#,0.00",
            "lineageTag": "44af4043-dce3-4503-96e7-eef77c04ed99"
          },
          {
            "name": "nmrc Ult Mes Q AGROSUPER M",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(SUM('Agristat live_mm_fact'[nmrc]), ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"Agrosuper S.A.\"",
              "             && 'Agristat live_mm_fact'[Apertura Indice]=\"m\"",
              "        )",
              ")"
            ],
            "lineageTag": "0f8bd68f-d899-48e9-bd35-eedbd80c126a"
          },
          {
            "name": "nmrc Ult 12 Meses Q AGROSUPER M",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(SUM('Agristat live_mm_fact'[nmrc]), ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"Agrosuper S.A.\" && 'Agristat live_mm_fact'[Apertura Indice]=\"m\"",
              "        )",
              ")"
            ],
            "lineageTag": "2e67ba68-612f-4456-adb1-f864cc4de523"
          },
          {
            "name": "Dif/mes $ M",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF([nmrc*1000 Ult 6 Meses AGROSUPER]-[nmrc*1000 Ult 6 Meses]<=1 && [nmrc*1000 Ult 6 Meses AGROSUPER]-[nmrc*1000 Ult 6 Meses]>=-1,BLANK(), [nmrc Ult Mes Q AGROSUPER M]*[Dif/Agrosuper]/1000)",
            "lineageTag": "f1624c7d-0c46-43ec-84d5-927b031d028d"
          },
          {
            "name": "Dif/año $ M",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF([nmrc*1000 Ult 6 Meses AGROSUPER]-[nmrc*1000 Ult 6 Meses]<=1 && [nmrc*1000 Ult 6 Meses AGROSUPER]-[nmrc*1000 Ult 6 Meses]>=-1,BLANK(), [nmrc Ult 12 Meses Q AGROSUPER M]*[Dif/Agrosuper] /1000 )",
            "lineageTag": "d880ef7c-356e-4896-aa9e-0b2612cf2ef7"
          },
          {
            "name": "nmrc Ult 6 Meses",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 6 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD]), ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda], 'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Indice Industrial Pollo]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-165<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 3 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD]), ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda], 'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Indice Industrial Pollo]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-85<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 12 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD]), ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda], 'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Indice Industrial Pollo]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Mes Anterior\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD]), ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda], 'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Indice Industrial Pollo]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-35<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])-5>='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              ")))))"
            ],
            "lineageTag": "3e834a5c-bc1f-41a6-90e0-6821b56c59a1"
          },
          {
            "name": "Dif/Agrosuper nmrc",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(([nmrc*1000 Ult 6 Meses AGROSUPER]/1000)-[nmrc Ult 6 Meses]<=0.000001 && ([nmrc*1000 Ult 6 Meses AGROSUPER]/1000)-[nmrc Ult 6 Meses]>=-0.00000001,BLANK(),",
              "([nmrc*1000 Ult 6 Meses AGROSUPER]/1000)-[nmrc Ult 6 Meses]",
              ")"
            ],
            "lineageTag": "d091f0d8-0d07-408b-b56d-21bf59792d82"
          },
          {
            "name": "Dif % nmrc",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "IF(([nmrc*1000 Ult 6 Meses AGROSUPER]/1000)-[nmrc Ult 6 Meses]<=0.0000001 && ([nmrc*1000 Ult 6 Meses AGROSUPER]/1000)-[nmrc Ult 6 Meses]>=-0.00000001,BLANK(),([nmrc*1000 Ult 6 Meses AGROSUPER]/1000)/[nmrc Ult 6 Meses]-1)",
            "formatString": "0.0\\ %;-0.0\\ %;0.0\\ %",
            "lineageTag": "c6f30646-14f9-49a6-be97-0447511b77d6"
          },
          {
            "name": "nmrc Ult Mes Q AGROSUPER ZA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(SUM('Agristat live_mm_fact'[nmrc]), ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"Agrosuper S.A.\"",
              "             && 'Agristat live_mm_fact'[Apertura Indice]=\"za\"",
              "        )",
              ")"
            ],
            "lineageTag": "2bc980d5-f085-475c-8d54-dd93c2b5cc58"
          },
          {
            "name": "nmrc Ult 12 Meses Q AGROSUPER ZA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(SUM('Agristat live_mm_fact'[nmrc]), ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"Agrosuper S.A.\" && 'Agristat live_mm_fact'[Apertura Indice]=\"za\"",
              "        )",
              ")"
            ],
            "lineageTag": "a579e01c-c692-4e81-8d84-4385b24af0bc"
          },
          {
            "name": "Dif/mes $ ZA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "IF(([nmrc*1000 Ult 6 Meses AGROSUPER]/1000)-[nmrc Ult 6 Meses]<=0.000000001 && ([nmrc*1000 Ult 6 Meses AGROSUPER]/1000)-[nmrc Ult 6 Meses]>=-0.00000001,BLANK(), [nmrc Ult Mes Q AGROSUPER ZA]*[Dif/Agrosuper nmrc])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "6061768c-dc80-42cc-812b-7d5bcc579492"
          },
          {
            "name": "Dif/año $ ZA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "IF(([nmrc*1000 Ult 6 Meses AGROSUPER]/1000)-[nmrc Ult 6 Meses]<=0.0000001 && ([nmrc*1000 Ult 6 Meses AGROSUPER]/1000)-[nmrc Ult 6 Meses]>=-0.00000001,BLANK(), [nmrc Ult 12 Meses Q AGROSUPER ZA]*[Dif/Agrosuper nmrc])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "6c7925a2-506e-476d-9eca-2783e8010978"
          },
          {
            "name": "nmrc Ult Mes Q AGROSUPER 5.98 E",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(SUM('Agristat live_mm_fact'[nmrc]), ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"Agrosuper S.A.\"",
              "             && 'Agristat live_mm_fact'[Apertura Indice]=\"e\" && 'Agristat live_mm_fact'[N Libro]=\"5.98\"",
              "        )",
              ")"
            ],
            "lineageTag": "ca173c9d-995f-43ee-b57e-81f0591f3e2f"
          },
          {
            "name": "nmrc Ult 12 Meses Q AGROSUPER 5.98 E",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(SUM('Agristat live_mm_fact'[nmrc]), ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"Agrosuper S.A.\" && 'Agristat live_mm_fact'[Apertura Indice]=\"e\" && 'Agristat live_mm_fact'[N Libro]=\"5.98\"",
              "        )",
              ")"
            ],
            "lineageTag": "cebaf1a5-fdd0-4899-b7ee-7f1fd77f1603"
          },
          {
            "name": "Dif/mes $ 5.98 E",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "IF([nmrc*1000 Ult 6 Meses AGROSUPER]-[nmrc*1000 Ult 6 Meses]<=0.0001 && [nmrc*1000 Ult 6 Meses AGROSUPER]-[nmrc*1000 Ult 6 Meses]>=-0.0001,BLANK(), [nmrc Ult Mes Q AGROSUPER 5.98 E]*[Dif/Agrosuper])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "85edb63d-ac9f-4b96-abce-a605685db2ea"
          },
          {
            "name": "Dif/año $ 5.98 E",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "IF([nmrc*1000 Ult 6 Meses AGROSUPER]-[nmrc*1000 Ult 6 Meses]<=0.0001 && [nmrc*1000 Ult 6 Meses AGROSUPER]-[nmrc*1000 Ult 6 Meses]>=-0.0001,BLANK(), [nmrc Ult 12 Meses Q AGROSUPER 5.98 E]*[Dif/Agrosuper])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "2e1b48ac-af74-4f92-a953-ec66c778f17e"
          },
          {
            "name": "nmrc Ult Mes Q AGROSUPER F",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(SUM('Agristat live_mm_fact'[nmrc]), ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"Agrosuper S.A.\"",
              "             && 'Agristat live_mm_fact'[Apertura Indice]=\"f\"",
              "        )",
              ")"
            ],
            "lineageTag": "288c6168-be11-4c2a-949b-5ec5c86efca5"
          },
          {
            "name": "nmrc Ult 12 Meses Q AGROSUPER F",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(SUM('Agristat live_mm_fact'[nmrc]), ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"Agrosuper S.A.\" && 'Agristat live_mm_fact'[Apertura Indice]=\"f\"",
              "        )",
              ")"
            ],
            "lineageTag": "9a8119ab-b4b5-4baa-8d75-169b285ca9aa"
          },
          {
            "name": "Dif/mes $ F",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "IF([nmrc*1000 Ult 6 Meses AGROSUPER]-[nmrc*1000 Ult 6 Meses]<=0.0001 && [nmrc*1000 Ult 6 Meses AGROSUPER]-[nmrc*1000 Ult 6 Meses]>=-0.0001,BLANK(), [nmrc Ult Mes Q AGROSUPER F]*[Dif/Agrosuper]*1000)",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "db1c70e1-8735-48b5-a5fa-d6ef8d6ab980"
          },
          {
            "name": "Dif/año $ F",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "IF([nmrc*1000 Ult 6 Meses AGROSUPER]-[nmrc*1000 Ult 6 Meses]<=0.0001 && [nmrc*1000 Ult 6 Meses AGROSUPER]-[nmrc*1000 Ult 6 Meses]>=-0.0001,BLANK(), [nmrc Ult 12 Meses Q AGROSUPER F]*[Dif/Agrosuper]*1000)",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "b3f27e89-1bfb-47be-bdc6-33b156bf1591"
          },
          {
            "name": "nmrc Peso 6.98 I",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(SUM('Agristat live_mm_fact'[nmrc]), ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Fecha Libro],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            'Agristat live_mm_fact'[Apertura Indice]=\"i\" && 'Agristat live_mm_fact'[N Libro]=\"6.98\"",
              "        )",
              ")"
            ],
            "lineageTag": "12775fa8-00d5-4535-9e3c-3681c04e5fdc"
          },
          {
            "name": "nmrc Conversión 6.98 J",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(SUM('Agristat live_mm_fact'[nmrc]), ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Fecha Libro],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            'Agristat live_mm_fact'[Apertura Indice]=\"j\" && 'Agristat live_mm_fact'[N Libro]=\"6.98\"",
              "        )",
              ")"
            ],
            "lineageTag": "7d9418a9-fca3-4781-8cd6-9c22db051b43"
          },
          {
            "name": "Dif/cab",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "[Dif/Agrosuper nmrc]/4 ",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "56f352b8-41de-4bf8-bf3e-5af936c432fa"
          },
          {
            "name": "$/mes",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "[Dif/cab]*350000",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "1d625e35-075f-42c6-ac23-86c24a56a6f4"
          },
          {
            "name": "$/12 meses",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "[$/mes]*12",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "14e289d4-8545-42e8-ab6a-e54a1532592f"
          },
          {
            "name": "nmrc*1000 Ult 6 Meses AGROSUPER Pollo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 6 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-165<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"AGROSUPER\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 3 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-85<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"AGROSUPER\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 12 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"AGROSUPER\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Mes Anterior\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-34<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])-5>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"AGROSUPER\"",
              "        )",
              ")))))"
            ],
            "lineageTag": "e8a69933-055d-47c5-84d8-3aa6e87e003a"
          },
          {
            "name": "Dif/Agrosuper nmrc Pollo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(([nmrc*1000 Ult 6 Meses AGROSUPER Pollo]/1000)-[nmrc Ult 6 Meses]<=0.000001 && ([nmrc*1000 Ult 6 Meses AGROSUPER Pollo]/1000)-[nmrc Ult 6 Meses]>=-0.00000001,BLANK(),",
              "([nmrc*1000 Ult 6 Meses AGROSUPER Pollo]/1000)-[nmrc Ult 6 Meses]",
              ")"
            ],
            "lineageTag": "cfffdfa4-9c77-435d-b0ca-ecad89d6d3c5"
          },
          {
            "name": "Dif % nmrc Pollo",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "IF(([nmrc*1000 Ult 6 Meses AGROSUPER Pollo]/1000)-[nmrc Ult 6 Meses]<=0.0000001 && ([nmrc*1000 Ult 6 Meses AGROSUPER Pollo]/1000)-[nmrc Ult 6 Meses]>=-0.00000001,BLANK(),([nmrc*1000 Ult 6 Meses AGROSUPER Pollo]/1000)/[nmrc Ult 6 Meses]-1)",
            "formatString": "0.0\\ %;-0.0\\ %;0.0\\ %",
            "lineageTag": "381e770b-2c22-4468-94c7-1f2a1f0a3f4d"
          },
          {
            "name": "nmrc Ult Mes Q AGROSUPER K Pollo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(SUM('Agristat live_mm_fact'[nmrc]), ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"AGROSUPER\"",
              "             && 'Agristat live_mm_fact'[Apertura Indice]=\"k\"",
              "        )",
              ")"
            ],
            "lineageTag": "82b49762-a0ab-49c1-8c4f-6c29912dfd3e"
          },
          {
            "name": "Dif/mes $ K Pollo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "IF([nmrc*1000 Ult 6 Meses AGROSUPER Pollo]-[nmrc*1000 Ult 6 Meses]<=0.0001 && [nmrc*1000 Ult 6 Meses AGROSUPER Pollo]-[nmrc*1000 Ult 6 Meses]>=-0.0001,BLANK(), [nmrc Ult Mes Q AGROSUPER K Pollo]*[Dif/Agrosuper nmrc Pollo]/1)",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "68758e52-26f2-45e0-9146-80f54d5dde6f"
          },
          {
            "name": "nmrc Ult 12 Meses Q AGROSUPER K Pollo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(SUM('Agristat live_mm_fact'[nmrc]), ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"AGROSUPER\" && 'Agristat live_mm_fact'[Apertura Indice]=\"k\"",
              "        )",
              ")"
            ],
            "lineageTag": "cfb7cf91-eae5-49cc-99eb-368990869f52"
          },
          {
            "name": "Dif/año $ K Pollo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "IF([nmrc*1000 Ult 6 Meses AGROSUPER Pollo]-[nmrc*1000 Ult 6 Meses]<=0.0001 && [nmrc*1000 Ult 6 Meses AGROSUPER Pollo]-[nmrc*1000 Ult 6 Meses]>=-0.0001,BLANK(), [nmrc Ult 12 Meses Q AGROSUPER K Pollo]*[Dif/Agrosuper nmrc Pollo]/1)",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "25ca9d58-6866-4070-ba23-64b00dead4ae"
          },
          {
            "name": "Ult. Mes Cascada Pollo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(SUM('Agristat live_mm_fact'[NMRC clp a USD]), ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[Desc Apertura Indice], 'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[sys_cd], 'Agristat live_mm_fact'[Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              ")"
            ],
            "lineageTag": "e4d48ec3-d6ea-48bb-9e1f-cc583f0ec942"
          },
          {
            "name": "Ult. Meses Cascada Pollo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 6 meses\",CALCULATE((SUM('Agristat live_mm_fact'[NMRC clp a USD]))/6, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-165<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"AGROSUPER\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 3 meses\",CALCULATE((SUM('Agristat live_mm_fact'[NMRC clp a USD]))/3, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-85<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"AGROSUPER\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 12 meses\",CALCULATE((SUM('Agristat live_mm_fact'[NMRC clp a USD]))/12, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"AGROSUPER\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Mes Anterior\",CALCULATE((SUM('Agristat live_mm_fact'[NMRC clp a USD]))/1, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-34<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])-5>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"AGROSUPER\"",
              "        )",
              ")))))"
            ],
            "lineageTag": "b7988382-7765-4ea1-948f-3ca952674de4"
          },
          {
            "name": "Display Pollo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "SWITCH(",
              "                SELECTEDVALUE('Filtro Cascada'[ID]),",
              "                1, [Ult. Meses Cascada Pollo],",
              "                2, [Ult. Mes Cascada Pollo]",
              ") "
            ],
            "lineageTag": "bdbb5e09-fd5b-4cfb-8622-84e4e23ac57a"
          },
          {
            "name": "Titulo Tabla con libro",
            "expression": [
              "--\"Comparación Promedio \"&SELECTEDVALUE('Filtro Comparación'[Comparación])&\" vs \" &FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"YYYY\")&\" - (\"&MAX('Agristat live_mm_fact'[Apertura Indice])&\")\"",
              "",
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 6 meses\",\"Impacto Económico Promedio \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-145,\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-145,\"YYYY\")&\" a \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"YYYY\")&\" - (\"&MAX('Agristat live_mm_fact'[Apertura Indice])&\")\",",
              "",
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 3 meses\",\"Impacto Económico Promedio \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-55,\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-55,\"YYYY\")&\" a \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"YYYY\")&\" - (\"&MAX('Agristat live_mm_fact'[Apertura Indice])&\")\",",
              "",
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 12 meses\",\"Impacto Económico Promedio \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-325,\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-325,\"YYYY\")&\" a \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"YYYY\")&\" - (\"&MAX('Agristat live_mm_fact'[Apertura Indice])&\")\",",
              "",
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Mes Anterior\",\"Impacto Económico Promedio \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-5,\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-5,\"YYYY\")&\" a \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"YYYY\")&\" - (\"&MAX('Agristat live_mm_fact'[Apertura Indice])&\")\"",
              "",
              "))))"
            ],
            "lineageTag": "77c14b13-f694-4202-ad5b-3febd9e8e02c"
          },
          {
            "name": "Titulo Tabla Cascada",
            "expression": [
              "\"Comparación Promedio \"&SELECTEDVALUE('Filtro Comparación'[Comparación])&\" vs \" &FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"YYYY\")",
              "/*IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 6 meses\",\"Impacto Económico Promedio \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-145,\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-145,\"YYYY\")&\" a \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"YYYY\"),",
              "",
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 3 meses\",\"Impacto Económico Promedio \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-55,\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-55,\"YYYY\")&\" a \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"YYYY\"),",
              "",
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 12 meses\",\"Impacto Económico Promedio \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-325,\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-325,\"YYYY\")&\" a \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"YYYY\"),",
              "",
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Mes Anterior\",\"Impacto Económico Promedio \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-5,\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-5,\"YYYY\")&\" a \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"YYYY\")",
              "",
              "))))*/"
            ],
            "lineageTag": "899a46ca-cc5a-4742-a5a6-d35fda988943"
          },
          {
            "name": "Dif/Agrosuper *1000",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "IF([nmrc*1000 Ult 6 Meses AGROSUPER]-[nmrc*1000 Ult 6 Meses]<=1 && [nmrc*1000 Ult 6 Meses AGROSUPER]-[nmrc*1000 Ult 6 Meses]>=-1,BLANK(),[nmrc*1000 Ult 6 Meses AGROSUPER]-[nmrc*1000 Ult 6 Meses])",
            "formatString": "#,0",
            "lineageTag": "c8d29fea-ce7d-4f83-975c-da9efb93eecf"
          },
          {
            "name": "Ult. Mes Cascada *1000",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(SUM('Agristat live_mm_fact'[NMRC clp a USD])*1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[Desc Apertura Indice], 'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[sys_cd], 'Agristat live_mm_fact'[Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              ")"
            ],
            "lineageTag": "5b6ea09c-1906-4df2-abfe-b1d780ed7bf1"
          },
          {
            "name": "Ult. Meses Cascada *1000",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 6 meses\",CALCULATE((SUM('Agristat live_mm_fact'[NMRC clp a USD])*1000)/6, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-165<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"Agrosuper S.A.\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 3 meses\",CALCULATE((SUM('Agristat live_mm_fact'[NMRC clp a USD])*1000)/3, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-85<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"Agrosuper S.A.\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 12 meses\",CALCULATE((SUM('Agristat live_mm_fact'[NMRC clp a USD])*1000)/12, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"Agrosuper S.A.\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Mes Anterior\",CALCULATE((SUM('Agristat live_mm_fact'[NMRC clp a USD])*1000)/1, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-34<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])-5>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"Agrosuper S.A.\"",
              "        )",
              ")))))"
            ],
            "lineageTag": "43bff416-d50b-48c4-9a91-17412a52ef0b"
          },
          {
            "name": "Display *1000",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "SWITCH(",
              "                SELECTEDVALUE('Filtro Cascada'[ID]),",
              "                1, [Ult. Meses Cascada *1000],",
              "                2, [Ult. Mes Cascada *1000]",
              ") "
            ],
            "formatString": "#,0",
            "lineageTag": "0931684f-cfbf-4cd5-9913-c794e2a31b39"
          },
          {
            "name": "nmrc Ult Mes Q AGROSUPER WEIGHT1 Pollo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(SUM('Agristat live_mm_fact'[nmrc]), ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"AGROSUPER\"",
              "             && 'Agristat live_mm_fact'[Apertura Indice]=\"WEIGHT1\"",
              "        )",
              ")"
            ],
            "lineageTag": "0308b1d7-172c-4f3f-b231-8a4830825ed3"
          },
          {
            "name": "nmrc Ult 12 Meses Q AGROSUPER WEIGHT1 Pollo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(SUM('Agristat live_mm_fact'[nmrc]), ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"AGROSUPER\" && 'Agristat live_mm_fact'[Apertura Indice]=\"WEIGHT1\"",
              "        )",
              ")"
            ],
            "lineageTag": "b72c5874-ff3f-4c86-a320-febc0c99a5dc"
          },
          {
            "name": "Dif/mes $ WEIGHT1 Pollo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "IF([nmrc*1000 Ult 6 Meses AGROSUPER Pollo]-[nmrc*1000 Ult 6 Meses]<=0.0001 && [nmrc*1000 Ult 6 Meses AGROSUPER Pollo]-[nmrc*1000 Ult 6 Meses]>=-0.0001,BLANK(), [nmrc Ult Mes Q AGROSUPER WEIGHT1 Pollo]*[Dif/Agrosuper nmrc Pollo]/1)",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "7f3cd110-9840-4413-aaa3-42a37b345fcd"
          },
          {
            "name": "Dif/año $ WEIGHT1 Pollo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "IF([nmrc*1000 Ult 6 Meses AGROSUPER Pollo]-[nmrc*1000 Ult 6 Meses]<=0.0001 && [nmrc*1000 Ult 6 Meses AGROSUPER Pollo]-[nmrc*1000 Ult 6 Meses]>=-0.0001,BLANK(), [nmrc Ult 12 Meses Q AGROSUPER WEIGHT1 Pollo]*[Dif/Agrosuper nmrc Pollo]/1)",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "4c3b9174-aa84-4ac7-a77d-dfd70c77574b"
          },
          {
            "name": "nmrc Ult Mes Q AGROSUPER M Pollo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(SUM('Agristat live_mm_fact'[nmrc]), ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"AGROSUPER\"",
              "             && 'Agristat live_mm_fact'[Apertura Indice]=\"m\"",
              "        )",
              ")"
            ],
            "lineageTag": "b7ef9f94-735a-4ab0-b8f3-734d84db551e"
          },
          {
            "name": "nmrc Ult 12 Meses Q AGROSUPER M Pollo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(SUM('Agristat live_mm_fact'[nmrc]), ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"AGROSUPER\" && 'Agristat live_mm_fact'[Apertura Indice]=\"m\"",
              "        )",
              ")"
            ],
            "lineageTag": "1c9afcbb-b2c0-45dd-add2-de4733a418b7"
          },
          {
            "name": "Dif/mes $ M Pollo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "IF([nmrc*1000 Ult 6 Meses AGROSUPER Pollo]-[nmrc*1000 Ult 6 Meses]<=0.0001 && [nmrc*1000 Ult 6 Meses AGROSUPER Pollo]-[nmrc*1000 Ult 6 Meses]>=-0.0001,BLANK(), [nmrc Ult Mes Q AGROSUPER M Pollo]*[Dif/Agrosuper nmrc Pollo]/1)",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "3ba4636e-4c1f-4d2c-a7a9-0eddbc774bb3"
          },
          {
            "name": "Dif/año $ M Pollo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "IF([nmrc*1000 Ult 6 Meses AGROSUPER Pollo]-[nmrc*1000 Ult 6 Meses]<=0.0001 && [nmrc*1000 Ult 6 Meses AGROSUPER Pollo]-[nmrc*1000 Ult 6 Meses]>=-0.0001,BLANK(), [nmrc Ult 12 Meses Q AGROSUPER M Pollo]*[Dif/Agrosuper nmrc Pollo]/1)",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "c6f9ba99-2db4-45bd-b36f-5de844ae8ff9"
          },
          {
            "name": "nmrc Ult 12 Meses 4.1 Compras AGROSUPER Pollo",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "CALCULATE(SUM('Agristat live_mm_fact'[nmrc])/12, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "713b58ed-c204-426d-8481-703b9dfbf35e"
          },
          {
            "name": "Dif/Agrosuper nmrc*1000 Pollo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "IF(([nmrc*1000 Ult 6 Meses AGROSUPER Pollo]/1000)-[nmrc Ult 6 Meses]<=0.000001 && ([nmrc*1000 Ult 6 Meses AGROSUPER Pollo]/1000)-[nmrc Ult 6 Meses]>=-0.00000001,BLANK(),",
              "([nmrc*1000 Ult 6 Meses AGROSUPER Pollo])-([nmrc Ult 6 Meses]*1000)",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "0061683a-c74e-4c82-8bae-22ff04f7b4a2"
          },
          {
            "name": "nmrc Ult Mes Q AGROSUPER R.1 Pollo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(SUM('Agristat live_mm_fact'[nmrc]), ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"AGROSUPER\"",
              "             && 'Agristat live_mm_fact'[Apertura Indice]=\"r.1\"",
              "        )",
              ")"
            ],
            "lineageTag": "2867efff-5e05-4013-a0a8-0ca584426a88"
          },
          {
            "name": "nmrc Ult 12 Meses Q AGROSUPER R.1 Pollo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(SUM('Agristat live_mm_fact'[nmrc]), ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"AGROSUPER\" && 'Agristat live_mm_fact'[Apertura Indice]=\"r.1\"",
              "        )",
              ")"
            ],
            "lineageTag": "05cce145-e83b-4cd1-98ff-4263f079cdb8"
          },
          {
            "name": "Dif/mes $ R.1 Pollo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "IF([nmrc*1000 Ult 6 Meses AGROSUPER Pollo]-[nmrc*1000 Ult 6 Meses]<=0.0001 && [nmrc*1000 Ult 6 Meses AGROSUPER Pollo]-[nmrc*1000 Ult 6 Meses]>=-0.0001,BLANK(), [nmrc Ult Mes Q AGROSUPER R.1 Pollo]*[Dif/Agrosuper nmrc Pollo]/100)",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "be7c48c8-3380-4ca8-ab7b-ab3e00ea71a4"
          },
          {
            "name": "Ult. Meses Cascada Pollo *1000",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 6 meses\",CALCULATE((SUM('Agristat live_mm_fact'[NMRC clp a USD])*1000)/6, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-165<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"AGROSUPER\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 3 meses\",CALCULATE((SUM('Agristat live_mm_fact'[NMRC clp a USD])*1000)/3, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-85<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"AGROSUPER\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 12 meses\",CALCULATE((SUM('Agristat live_mm_fact'[NMRC clp a USD])*1000)/12, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"AGROSUPER\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Mes Anterior\",CALCULATE((SUM('Agristat live_mm_fact'[NMRC clp a USD])*1000)/1, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-34<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])-5>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"AGROSUPER\"",
              "        )",
              ")))))"
            ],
            "lineageTag": "e19daffb-2b9e-442d-b211-b2635d18bd24"
          },
          {
            "name": "Ult. Mes Cascada Pollo *1000",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(SUM('Agristat live_mm_fact'[NMRC clp a USD])*1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[Desc Apertura Indice], 'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[sys_cd], 'Agristat live_mm_fact'[Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              ")"
            ],
            "lineageTag": "af352441-9a33-4b82-b58a-fbdcb725bba4"
          },
          {
            "name": "Display Pollo *1000",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "SWITCH(",
              "                SELECTEDVALUE('Filtro Cascada'[ID]),",
              "                1, [Ult. Meses Cascada Pollo *1000],",
              "                2, [Ult. Mes Cascada Pollo *1000]",
              ") "
            ],
            "formatString": "#,0",
            "lineageTag": "4e6c9577-64a4-4449-b96f-7a89b4c85d14"
          },
          {
            "name": "Dif/año $ R.1 Pollo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "IF([nmrc*1000 Ult 6 Meses AGROSUPER Pollo]-[nmrc*1000 Ult 6 Meses]<=0.0001 && [nmrc*1000 Ult 6 Meses AGROSUPER Pollo]-[nmrc*1000 Ult 6 Meses]>=-0.0001,BLANK(), [nmrc Ult 12 Meses Q AGROSUPER R.1 Pollo]*[Dif/Agrosuper nmrc Pollo]/100)",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "ab9444b5-7974-486c-8b0c-c381046b52da"
          },
          {
            "name": "Titulo Tabla Promedio Ult 12 meses",
            "expression": "\"Promedio \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-325,\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-325,\"YYYY\")&\" a \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"YYYY\")",
            "lineageTag": "bbfb9deb-6d89-450d-9fbf-0e2fbdb2d630"
          },
          {
            "name": "nmrc*10 Ult 6 Meses",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 6 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*10, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Indice Industrial Pollo],'Agristat live_mm_fact'[Desc Apertura Indice REEM kg]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-165<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 3 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*10, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Indice Industrial Pollo],'Agristat live_mm_fact'[Desc Apertura Indice REEM kg]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-85<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 12 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*10, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Indice Industrial Pollo],'Agristat live_mm_fact'[Desc Apertura Indice REEM kg]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Mes Anterior\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*10, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Indice Industrial Pollo],'Agristat live_mm_fact'[Desc Apertura Indice REEM kg]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-35<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])-5>='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              ")))))"
            ],
            "formatString": "#,0.00",
            "lineageTag": "b722868c-1aa8-47ad-a924-04ecbda277d6"
          },
          {
            "name": "Dif/Agrosuper nmrc*10 Pollo",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "IF(([nmrc*1000 Ult 6 Meses AGROSUPER Pollo]/1000)-[nmrc Ult 6 Meses]<=0.000001 && ([nmrc*1000 Ult 6 Meses AGROSUPER Pollo]/1000)-[nmrc Ult 6 Meses]>=-0.00000001,BLANK(),",
              "([nmrc*1000 Ult 6 Meses AGROSUPER Pollo]/100)-([nmrc Ult 6 Meses]*10)",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "d6f78f6b-2265-4e38-9d3e-c0e5315bd665"
          },
          {
            "name": "Ult. Meses Cascada Pollo *10",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 6 meses\",CALCULATE((SUM('Agristat live_mm_fact'[NMRC clp a USD])*10)/6, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-165<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"AGROSUPER\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 3 meses\",CALCULATE((SUM('Agristat live_mm_fact'[NMRC clp a USD])*10)/3, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-85<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"AGROSUPER\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 12 meses\",CALCULATE((SUM('Agristat live_mm_fact'[NMRC clp a USD])*10)/12, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"AGROSUPER\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Mes Anterior\",CALCULATE((SUM('Agristat live_mm_fact'[NMRC clp a USD])*10)/1, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-34<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])-5>='Agristat live_mm_fact'[Fecha Libro] &&'Agristat live_mm_fact'[Indice]=\"AGROSUPER\"",
              "        )",
              ")))))"
            ],
            "lineageTag": "728b05ed-317a-4453-91a1-69aa16065e26"
          },
          {
            "name": "Ult. Mes Cascada Pollo *10",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(SUM('Agristat live_mm_fact'[NMRC clp a USD])*10, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[Desc Apertura Indice], 'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[sys_cd], 'Agristat live_mm_fact'[Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              ")"
            ],
            "lineageTag": "5ea8eaad-52da-4957-a684-d1cf259c5c72"
          },
          {
            "name": "Display Pollo *10",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "SWITCH(",
              "                SELECTEDVALUE('Filtro Cascada'[ID]),",
              "                1, [Ult. Meses Cascada Pollo *10],",
              "                2, [Ult. Mes Cascada Pollo *10]",
              ") "
            ],
            "formatString": "#,0",
            "lineageTag": "dbaa0e41-6a9a-447f-9b77-91f67a07f333"
          },
          {
            "name": "Brecha T25 LM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM('Agristat live_mm_fact'[nmrc*10 LM])-SUM('Agristat live_mm_fact'[nmrc*10 T25])",
            "lineageTag": "0f283a4b-096a-43c0-862b-7befa78064b2"
          },
          {
            "name": "Brecha T25 SV",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM('Agristat live_mm_fact'[nmrc*10 SV])-SUM('Agristat live_mm_fact'[nmrc*10 T25])",
            "lineageTag": "a0708d5c-e112-41d6-90b6-9d587b53f3f2"
          },
          {
            "name": "nmrc/1000 Ult 6 Meses",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 6 meses\",CALCULATE(SUM('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Indice Industrial Pollo]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-165<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 3 meses\",CALCULATE(SUM('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Indice Industrial Pollo]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-85<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 12 meses\",CALCULATE(SUM('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Indice Industrial Pollo]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Mes Anterior\",CALCULATE(SUM('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Indice Industrial Pollo]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-35<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])-5>='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              ")))))"
            ],
            "formatString": "#,0",
            "lineageTag": "4c60c62f-6ca7-45a8-9577-ab3639eb16fd"
          },
          {
            "name": "Titulo Tabla Ton Carne",
            "expression": [
              "--\"Comparación Promedio \"&SELECTEDVALUE('Filtro Comparación'[Comparación])&\" vs \" &FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"YYYY\")&\" - (\"&MAX('Agristat live_mm_fact'[Apertura Indice])&\")\"",
              "",
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 6 meses\",\"Ton Carne - \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-145,\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-145,\"YYYY\")&\" a \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"YYYY\")&\" - (\"&MAX('Agristat live_mm_fact'[Apertura Indice])&\")\",",
              "",
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 3 meses\",\"Ton Carne - \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-55,\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-55,\"YYYY\")&\" a \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"YYYY\")&\" - (\"&MAX('Agristat live_mm_fact'[Apertura Indice])&\")\",",
              "",
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 12 meses\",\"Ton Carne - \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-325,\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-325,\"YYYY\")&\" a \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"YYYY\")&\" - (\"&MAX('Agristat live_mm_fact'[Apertura Indice])&\")\",",
              "",
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Mes Anterior\",\"Ton Carne - \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-5,\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro])-5,\"YYYY\")&\" a \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"mmmm\")&\" \"&FORMAT(MAX('Agristat live_mm_fact'[Fecha Libro]),\"YYYY\")&\" - (\"&MAX('Agristat live_mm_fact'[Apertura Indice])&\")\"",
              "",
              "))))"
            ],
            "lineageTag": "5fe3b862-433f-4159-b7b9-472bf7d43e1d"
          },
          {
            "name": "nmrc*10 Ult 6 Meses LO MIRANDA Pollo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 6 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*10, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-165<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Pollo]=\"Lo Miranda\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 3 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*10, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-85<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Pollo]=\"Lo Miranda\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 12 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*10, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Pollo]=\"Lo Miranda\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Mes Anterior\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*10, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-34<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])-5>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Pollo]=\"Lo Miranda\"",
              "        )",
              ")))))"
            ],
            "lineageTag": "b2957a0c-6614-4a69-9870-8483550fce14"
          },
          {
            "name": "Dif/Lo Miranda nmrc*10 Pollo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(([nmrc*10 Ult 6 Meses LO MIRANDA Pollo]/10)-[nmrc Ult 6 Meses]<=0.000001 && ([nmrc*10 Ult 6 Meses LO MIRANDA Pollo]/10)-[nmrc Ult 6 Meses]>=-0.00000001,BLANK(),",
              "([nmrc*10 Ult 6 Meses LO MIRANDA Pollo])-([nmrc Ult 6 Meses]*10)",
              ")"
            ],
            "lineageTag": "05effcc7-1990-4dc2-bbc9-eb358b4168f4"
          },
          {
            "name": "nmrc*10 Ult 6 Meses SAN VICENTE Pollo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 6 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*10, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-165<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Pollo]=\"San Vicente\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 3 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*10, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-85<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Pollo]=\"San Vicente\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 12 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*10, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Pollo]=\"San Vicente\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Mes Anterior\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*10, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-34<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])-5>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Pollo]=\"San Vicente\"",
              "        )",
              ")))))"
            ],
            "lineageTag": "e9f934fe-6f0f-4f61-8c92-6b47b53e3ec6"
          },
          {
            "name": "Dif/San Vicente nmrc*10 Pollo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(([nmrc*10 Ult 6 Meses SAN VICENTE Pollo]/10)-[nmrc Ult 6 Meses]<=0.000001 && ([nmrc*10 Ult 6 Meses SAN VICENTE Pollo]/10)-[nmrc Ult 6 Meses]>=-0.00000001,BLANK(),",
              "([nmrc*10 Ult 6 Meses SAN VICENTE Pollo])-([nmrc Ult 6 Meses]*10)",
              ")"
            ],
            "lineageTag": "8ff38b5e-d49e-454c-b157-09171e7e9a77"
          },
          {
            "name": "Ton WOG LO MIRANDA Pollo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 6 meses\",CALCULATE(SUM('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-165<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Pollo]=\"Lo Miranda\" && 'Agristat live_mm_fact'[N Libro]=\"3.1\" && 'Agristat live_mm_fact'[Apertura Indice]=\"aa\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 3 meses\",CALCULATE(SUM('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-85<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Pollo]=\"Lo Miranda\" && 'Agristat live_mm_fact'[N Libro]=\"3.1\" && 'Agristat live_mm_fact'[Apertura Indice]=\"aa\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 12 meses\",CALCULATE(SUM('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Pollo]=\"Lo Miranda\" && 'Agristat live_mm_fact'[N Libro]=\"3.1\" && 'Agristat live_mm_fact'[Apertura Indice]=\"aa\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Mes Anterior\",CALCULATE(SUM('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-34<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])-5>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Pollo]=\"Lo Miranda\" && 'Agristat live_mm_fact'[N Libro]=\"3.1\" && 'Agristat live_mm_fact'[Apertura Indice]=\"aa\"",
              "        )",
              ")))))"
            ],
            "lineageTag": "5e7505ff-011f-4e12-8eb0-ca656847008a"
          },
          {
            "name": "Ton WOG SAN VICENTE Pollo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 6 meses\",CALCULATE(SUM('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-165<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Pollo]=\"San Vicente\" && 'Agristat live_mm_fact'[N Libro]=\"3.1\" && 'Agristat live_mm_fact'[Apertura Indice]=\"aa\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 3 meses\",CALCULATE(SUM('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-85<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Pollo]=\"San Vicente\" && 'Agristat live_mm_fact'[N Libro]=\"3.1\" && 'Agristat live_mm_fact'[Apertura Indice]=\"aa\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 12 meses\",CALCULATE(SUM('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Pollo]=\"San Vicente\" && 'Agristat live_mm_fact'[N Libro]=\"3.1\" && 'Agristat live_mm_fact'[Apertura Indice]=\"aa\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Mes Anterior\",CALCULATE(SUM('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-34<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])-5>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Pollo]=\"San Vicente\" && 'Agristat live_mm_fact'[N Libro]=\"3.1\" && 'Agristat live_mm_fact'[Apertura Indice]=\"aa\"",
              "        )",
              ")))))"
            ],
            "lineageTag": "218bceb5-24e5-428e-936c-aa9218540bb2"
          },
          {
            "name": "Ton WOG AGROSUPER Pollo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 6 meses\",CALCULATE(SUM('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-165<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && ('Agristat live_mm_fact'[Indice Industrial Pollo]=\"Lo Miranda\" || 'Agristat live_mm_fact'[Indice Industrial Pollo]=\"San Vicente\") && 'Agristat live_mm_fact'[N Libro]=\"3.1\" && 'Agristat live_mm_fact'[Apertura Indice]=\"aa\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 3 meses\",CALCULATE(SUM('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-85<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && ('Agristat live_mm_fact'[Indice Industrial Pollo]=\"Lo Miranda\" || 'Agristat live_mm_fact'[Indice Industrial Pollo]=\"San Vicente\") && 'Agristat live_mm_fact'[N Libro]=\"3.1\" && 'Agristat live_mm_fact'[Apertura Indice]=\"aa\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 12 meses\",CALCULATE(SUM('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && ('Agristat live_mm_fact'[Indice Industrial Pollo]=\"Lo Miranda\" || 'Agristat live_mm_fact'[Indice Industrial Pollo]=\"San Vicente\") && 'Agristat live_mm_fact'[N Libro]=\"3.1\" && 'Agristat live_mm_fact'[Apertura Indice]=\"aa\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Mes Anterior\",CALCULATE(SUM('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-34<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])-5>='Agristat live_mm_fact'[Fecha Libro] && ('Agristat live_mm_fact'[Indice Industrial Pollo]=\"Lo Miranda\" || 'Agristat live_mm_fact'[Indice Industrial Pollo]=\"San Vicente\") && 'Agristat live_mm_fact'[N Libro]=\"3.1\" && 'Agristat live_mm_fact'[Apertura Indice]=\"aa\"",
              "        )",
              ")))))"
            ],
            "lineageTag": "ac8219d8-3991-40d9-9aa8-3a8112116630"
          },
          {
            "name": "Impacto Dif AS (/Ton)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "[Dif/Agrosuper nmrc*10 Pollo]*'Agristat live_mm_fact'[Ton WOG AGROSUPER Pollo]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "73fe0304-6ca9-4ccb-99c8-5f09959c5e45"
          },
          {
            "name": "Impacto Dif LM (/Ton)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "[Dif/Lo Miranda nmrc*10 Pollo]*'Agristat live_mm_fact'[Ton WOG LO MIRANDA Pollo]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "87799270-0ca1-4dfc-9c49-eda2906ae3cc"
          },
          {
            "name": "Impacto Dif SV (/Ton)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "[Dif/San Vicente nmrc*10 Pollo]*'Agristat live_mm_fact'[Ton WOG SAN VICENTE Pollo]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "63f8538d-8ce4-48d0-8564-26fde7aba829"
          },
          {
            "name": "nmrc/100",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "SUM('Agristat live_mm_fact'[NMRC clp a USD])/100",
            "formatString": "0.0\\ %;-0.0\\ %;0.0\\ %",
            "lineageTag": "7c15381c-38d5-499f-b551-2416d35aa011"
          },
          {
            "name": "Brecha T25 LM Cerdo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM('Agristat live_mm_fact'[nmrc*10 LM Cerdo])-SUM('Agristat live_mm_fact'[nmrc*10 T25 Cerdo])",
            "lineageTag": "0eb82e0e-3641-4d1f-a10e-9b55f243fefd"
          },
          {
            "name": "Brecha T25 RS Cerdo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM('Agristat live_mm_fact'[nmrc*10 RS Cerdo])-SUM('Agristat live_mm_fact'[nmrc*10 T25 Cerdo])",
            "lineageTag": "26b63c43-4216-41c9-aae7-3b58fba2a19f"
          },
          {
            "name": "nmrc*10 Ult 6 Meses Cerdo",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 6 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*10, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Indice Industrial Cerdo],'Agristat live_mm_fact'[Desc Apertura Indice REEM kg]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-165<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 3 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*10, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Indice Industrial Cerdo],'Agristat live_mm_fact'[Desc Apertura Indice REEM kg]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-85<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 12 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*10, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Indice Industrial Cerdo],'Agristat live_mm_fact'[Desc Apertura Indice REEM kg]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Mes Anterior\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*10, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Indice Industrial Cerdo],'Agristat live_mm_fact'[Desc Apertura Indice REEM kg]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-35<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])-5>='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              ")))))"
            ],
            "formatString": "#,0.00",
            "lineageTag": "041e7775-79ab-4fee-89ab-d4d77f922478"
          },
          {
            "name": "Dif/Agrosuper nmrc*10 Cerdo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(([nmrc*10 Ult 6 Meses AGROSUPER Cerdo])-[nmrc*10 Ult 6 Meses Cerdo]<=0.000001 && ([nmrc*10 Ult 6 Meses AGROSUPER Cerdo])-[nmrc*10 Ult 6 Meses Cerdo]>=-0.00000001,BLANK(),",
              "([nmrc*10 Ult 6 Meses AGROSUPER Cerdo])-([nmrc*10 Ult 6 Meses Cerdo])",
              ")"
            ],
            "lineageTag": "015c5c1f-fd05-47b5-b5aa-d5f2eab0d22f"
          },
          {
            "name": "nmrc*10 Ult 6 Meses AGROSUPER Cerdo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 6 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*10,",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Desc Apertura Indice REEM kg]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-165<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Cerdo]=\"AGROSUPER\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 3 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*10,",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Desc Apertura Indice REEM kg]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-85<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Cerdo]=\"AGROSUPER\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 12 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*10,",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Desc Apertura Indice REEM kg]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Cerdo]=\"AGROSUPER\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Mes Anterior\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*10,",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Desc Apertura Indice REEM kg]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-34<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])-5>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Cerdo]=\"AGROSUPER\"",
              "        )",
              ")))))"
            ],
            "lineageTag": "5f2d873e-3928-4dde-b965-1fb96279ecbc"
          },
          {
            "name": "nmrc*10 Ult 6 Meses LO MIRANDA Cerdo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 6 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*10,",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Desc Apertura Indice REEM kg]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-165<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Cerdo]=\"LO MIRANDA\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 3 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*10,",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Desc Apertura Indice REEM kg]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-85<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Cerdo]=\"LO MIRANDA\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 12 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*10,",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Desc Apertura Indice REEM kg]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Cerdo]=\"LO MIRANDA\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Mes Anterior\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*10,",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Desc Apertura Indice REEM kg]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-34<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])-5>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Cerdo]=\"LO MIRANDA\"",
              "        )",
              ")))))"
            ],
            "lineageTag": "753f4375-566f-4803-a069-44dd4ee1b804"
          },
          {
            "name": "nmrc*10 Ult 6 Meses ROSARIO Cerdo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 6 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*10,",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Desc Apertura Indice REEM kg]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-165<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Cerdo]=\"ROSARIO\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 3 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*10,",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Desc Apertura Indice REEM kg]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-85<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Cerdo]=\"ROSARIO\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 12 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*10,",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Desc Apertura Indice REEM kg]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Cerdo]=\"ROSARIO\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Mes Anterior\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])*10,",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Cod. Indice y Descripción],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice],'Agristat live_mm_fact'[Desc Apertura Indice REEM kg]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-34<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])-5>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Cerdo]=\"ROSARIO\"",
              "        )",
              ")))))"
            ],
            "lineageTag": "36bce853-9ac6-4ff6-aa94-7090b2e536da"
          },
          {
            "name": "Dif/Lo Miranda nmrc*10 Cerdo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(([nmrc*10 Ult 6 Meses LO MIRANDA Cerdo])-[nmrc*10 Ult 6 Meses Cerdo]<=0.000001 && ([nmrc*10 Ult 6 Meses LO MIRANDA Cerdo])-[nmrc*10 Ult 6 Meses Cerdo]>=-0.00000001,BLANK(),",
              "([nmrc*10 Ult 6 Meses LO MIRANDA Cerdo])-([nmrc*10 Ult 6 Meses Cerdo])",
              ")"
            ],
            "lineageTag": "8ffe784c-fef5-45b8-b250-06688d25ad7a"
          },
          {
            "name": "Dif/Rosario nmrc*10 Cerdo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(([nmrc*10 Ult 6 Meses ROSARIO Cerdo])-[nmrc*10 Ult 6 Meses Cerdo]<=0.000001 && ([nmrc*10 Ult 6 Meses ROSARIO Cerdo])-[nmrc*10 Ult 6 Meses Cerdo]>=-0.00000001,BLANK(),",
              "([nmrc*10 Ult 6 Meses ROSARIO Cerdo])-([nmrc*10 Ult 6 Meses Cerdo])",
              ")"
            ],
            "lineageTag": "9b32120f-768a-4502-8b4a-e085f443c9d4"
          },
          {
            "name": "nmrc/1000 Ult 6 Meses Cerdo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 6 meses\",CALCULATE(SUM('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Indice Industrial Cerdo]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-165<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 3 meses\",CALCULATE(SUM('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Indice Industrial Cerdo]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-85<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 12 meses\",CALCULATE(SUM('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Indice Industrial Cerdo]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Mes Anterior\",CALCULATE(SUM('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Indice Industrial Cerdo]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-35<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])-5>='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              ")))))"
            ],
            "lineageTag": "7feb570b-7ce2-4f67-bf11-a18467a4e013"
          },
          {
            "name": "Impacto Dif AS (/Ton) Cerdo",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "[Dif/Agrosuper nmrc*10 Cerdo]*'Agristat live_mm_fact'[Ton Prod Corte AGROSUPER Cerdo]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "82678ab9-6da8-42ef-a755-55c5b6bb4c8b"
          },
          {
            "name": "Ton Prod Corte AGROSUPER Cerdo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 6 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-165<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && ('Agristat live_mm_fact'[Indice Industrial Cerdo]=\"LO MIRANDA\" || 'Agristat live_mm_fact'[Indice Industrial Cerdo]=\"ROSARIO\") && 'Agristat live_mm_fact'[N Libro]=\"1.2\" && 'Agristat live_mm_fact'[Apertura Indice]=\"zWEIGHT2\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 3 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-85<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && ('Agristat live_mm_fact'[Indice Industrial Cerdo]=\"LO MIRANDA\" || 'Agristat live_mm_fact'[Indice Industrial Cerdo]=\"ROSARIO\") && 'Agristat live_mm_fact'[N Libro]=\"1.2\" && 'Agristat live_mm_fact'[Apertura Indice]=\"zWEIGHT2\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 12 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && ('Agristat live_mm_fact'[Indice Industrial Cerdo]=\"LO MIRANDA\" || 'Agristat live_mm_fact'[Indice Industrial Cerdo]=\"ROSARIO\") && 'Agristat live_mm_fact'[N Libro]=\"1.2\" && 'Agristat live_mm_fact'[Apertura Indice]=\"zWEIGHT2\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Mes Anterior\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-34<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])-5>='Agristat live_mm_fact'[Fecha Libro] && ('Agristat live_mm_fact'[Indice Industrial Cerdo]=\"LO MIRANDA\" || 'Agristat live_mm_fact'[Indice Industrial Cerdo]=\"ROSARIO\") && 'Agristat live_mm_fact'[N Libro]=\"1.2\" && 'Agristat live_mm_fact'[Apertura Indice]=\"zWEIGHT2\"",
              "        )",
              ")))))"
            ],
            "lineageTag": "5a4cc0ce-d42d-4ffc-ac50-283b64e380de"
          },
          {
            "name": "Ton Prod Corte LO MIRANDA Cerdo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 6 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-165<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Cerdo]=\"LO MIRANDA\" && 'Agristat live_mm_fact'[N Libro]=\"1.2\" && 'Agristat live_mm_fact'[Apertura Indice]=\"zWEIGHT2\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 3 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-85<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Cerdo]=\"LO MIRANDA\" && 'Agristat live_mm_fact'[N Libro]=\"1.2\" && 'Agristat live_mm_fact'[Apertura Indice]=\"zWEIGHT2\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 12 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Cerdo]=\"LO MIRANDA\" && 'Agristat live_mm_fact'[N Libro]=\"1.2\" && 'Agristat live_mm_fact'[Apertura Indice]=\"zWEIGHT2\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Mes Anterior\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-34<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])-5>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Cerdo]=\"LO MIRANDA\" && 'Agristat live_mm_fact'[N Libro]=\"1.2\" && 'Agristat live_mm_fact'[Apertura Indice]=\"zWEIGHT2\"",
              "        )",
              ")))))"
            ],
            "lineageTag": "63307e01-971b-4a2f-9953-cb3ecd20a881"
          },
          {
            "name": "Ton Prod Corte ROSARIO Cerdo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 6 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-165<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Cerdo]=\"ROSARIO\" && 'Agristat live_mm_fact'[N Libro]=\"1.2\" && 'Agristat live_mm_fact'[Apertura Indice]=\"zWEIGHT2\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 3 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-85<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Cerdo]=\"ROSARIO\" && 'Agristat live_mm_fact'[N Libro]=\"1.2\" && 'Agristat live_mm_fact'[Apertura Indice]=\"zWEIGHT2\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 12 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Cerdo]=\"ROSARIO\" && 'Agristat live_mm_fact'[N Libro]=\"1.2\" && 'Agristat live_mm_fact'[Apertura Indice]=\"zWEIGHT2\"",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Mes Anterior\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Desc Apertura Indice]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-34<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])-5>='Agristat live_mm_fact'[Fecha Libro] && 'Agristat live_mm_fact'[Indice Industrial Cerdo]=\"ROSARIO\" && 'Agristat live_mm_fact'[N Libro]=\"1.2\" && 'Agristat live_mm_fact'[Apertura Indice]=\"zWEIGHT2\"",
              "        )",
              ")))))"
            ],
            "lineageTag": "ad43813e-b92a-484b-9e4a-668c15d6a694"
          },
          {
            "name": "Impacto Dif LM (/Ton) Cerdo",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "[Dif/Lo Miranda nmrc*10 Cerdo]*'Agristat live_mm_fact'[Ton Prod Corte LO MIRANDA Cerdo]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "1d9a4607-6390-46ae-85ed-7ac78d440931"
          },
          {
            "name": "Impacto Dif RS (/Ton) Cerdo",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "[Dif/Rosario nmrc*10 Cerdo]*'Agristat live_mm_fact'[Ton Prod Corte ROSARIO Cerdo]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "b3e3cc5d-9d1b-43b5-b4ce-2466a37d25b0"
          },
          {
            "name": "nmrc/1000 Ult 6 Meses Cerdo PROM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 6 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Indice Industrial Cerdo]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-165<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 3 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Indice Industrial Cerdo]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-85<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Ult. 12 meses\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Indice Industrial Cerdo]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-340<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])>='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              "),IF(SELECTEDVALUE('Filtro Comparación'[Comparación])=\"Mes Anterior\",CALCULATE(AVERAGE('Agristat live_mm_fact'[NMRC clp a USD])/1000, ",
              "FILTER(",
              "    ALLEXCEPT('Agristat live_mm_fact','Agristat live_mm_fact'[Moneda],'Agristat live_mm_fact'[Sector],'Agristat live_mm_fact'[N Libro],'Agristat live_mm_fact'[Indice],'Agristat live_mm_fact'[Apertura Indice],'Agristat live_mm_fact'[sys_cd],'Agristat live_mm_fact'[Indice Industrial Cerdo]),",
              "            MAX('Agristat live_mm_fact'[Fecha Libro])-35<='Agristat live_mm_fact'[Fecha Libro] && MAX('Agristat live_mm_fact'[Fecha Libro])-5>='Agristat live_mm_fact'[Fecha Libro]",
              "        )",
              ")))))"
            ],
            "lineageTag": "0c4da3a3-f41f-4d9a-8dea-9cf7c7625660"
          },
          {
            "name": "Brecha LM vs Filtro",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM('Agristat live_mm_fact'[nmrc*10 LM Cerdo Fijo Colum])-[nmrc*10]",
            "lineageTag": "8776a5a0-7e89-41ee-859d-10074711a032"
          },
          {
            "name": "Brecha RS vs Filtro",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM('Agristat live_mm_fact'[nmrc*10 RS Cerdo Fijo Colum])-[nmrc*10]",
            "lineageTag": "aeb7c67e-2b90-462e-8032-b60c504f14ea"
          },
          {
            "name": "Titulo Brecha Plantas Agrosuper",
            "expression": "\"Evolución Brecha Plantas Agrosuper vs \"&MAX('Agristat live_mm_fact'[Indice Industrial Cerdo])",
            "lineageTag": "6427a12b-c2cc-405a-8234-f8a8d03a383d"
          }
        ],
        "partitions": [
          {
            "name": "Agristat live_mm_fact-77432e95-b940-45ad-918a-7d2b0c699375",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Sql.Database(\"10.195.4.4\", \"sqldb-as-gplanificacionygestion-pyg-prd\"),",
                "    Agristat_live_mm_fact = Origen{[Schema=\"Agristat\",Item=\"live_mm_fact_hist\"]}[Data],",
                "    #\"Columnas con nombre cambiado\" = Table.RenameColumns(Agristat_live_mm_fact,{{\"fact_dsc_nm\", \"Indice\"}, {\"fact_dsc_cd\", \"Cod. Indice\"}}),",
                "    #\"Consulta anexada\" = Table.Combine({#\"Columnas con nombre cambiado\", #\"Agristat live_mm_fact AGROSUPER AA\"})",
                "in",
                "    #\"Consulta anexada\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_67a10a6a-6e8d-4348-aef2-26425e82f0be",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b93ae1ab-99a4-4586-bdf4-03ece4fe26a9",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "76fc362f-4c37-4da4-acda-421e0da83d0b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "71bde2f7-aec6-4449-8c74-5546b98ac3a0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "64532983-e18e-4c6c-9759-0e70b80e78eb",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1336ba75-2744-4caf-aab0-d6bc79868a40",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1b2fcca3-e696-480e-acc2-4028a5aeb508",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f9f768d2-2d7f-4f71-981f-26fb521c7ac6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "1741649f-489b-47e8-981f-e29c8d65e463",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "268eb711-e79e-4339-b5fe-6ddf52991349",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "482e5df7-1109-4c19-b709-ced6b37cd186",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "ff3168f7-bbd8-4cbb-9c88-8b6bc8d1e72b",
                "ordinal": 3
              }
            ],
            "lineageTag": "e1ee0c65-2107-4880-81f3-c6136d139fa8"
          }
        ],
        "isHidden": true,
        "lineageTag": "0347a3b2-ca56-4a16-b464-729d6899158f",
        "partitions": [
          {
            "name": "LocalDateTable_67a10a6a-6e8d-4348-aef2-26425e82f0be-2b1c63c4-40bf-4d0c-8b19-d868b5660d1a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Agristat live_mm_fact'[last_db_updt_ts])), 1, 1), Date(Year(MAX('Agristat live_mm_fact'[last_db_updt_ts])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Agristat plnt_alias",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "sys_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ff972a0-b4e4-4feb-a788-5fb2be630da9",
            "sourceColumn": "sys_cd",
            "summarizeBy": "none"
          },
          {
            "name": "sctn_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0bd11a22-6898-426f-9481-13afc8ab61bf",
            "sourceColumn": "sctn_cd",
            "summarizeBy": "none"
          },
          {
            "name": "plnt_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "97c62c33-b63d-44d1-9244-df0fd35b8a31",
            "sourceColumn": "plnt_cd",
            "summarizeBy": "none"
          },
          {
            "name": "shrt_alias_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "21a6461d-45c9-445a-9a0b-18a689c2ae78",
            "sourceColumn": "shrt_alias_cd",
            "summarizeBy": "none"
          },
          {
            "name": "long_alias_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4abd41c0-a33e-4902-9b1c-dcbb0c5b1d7b",
            "sourceColumn": "long_alias_nm",
            "summarizeBy": "none"
          },
          {
            "name": "plnt_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "12d6d773-8b43-4078-af7b-cd497bb58b7b",
            "sourceColumn": "plnt_nm",
            "summarizeBy": "none"
          },
          {
            "name": "mm_tm_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "abc4a03a-1878-452e-b159-39c94d7cc284",
            "sourceColumn": "mm_tm_id",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "2796414d-97e7-467f-8e8c-45d3d9b63229",
        "partitions": [
          {
            "name": "Agristat plnt_alias-3f934cf5-7d6d-4a32-b9b4-7fd40e757ecb",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Sql.Database(\"10.195.4.4\", \"sqldb-as-gplanificacionygestion-pyg-prd\"),",
                "    Agristat_plnt_alias = Origen{[Schema=\"Agristat\",Item=\"plnt_alias\"]}[Data]",
                "in",
                "    Agristat_plnt_alias"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Maestra Indice",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Sector",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "43bb8fc8-1faa-4211-8013-127dfd59f0a4",
            "sourceColumn": "Sector",
            "summarizeBy": "none"
          },
          {
            "name": "Item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e8e16c8-3769-4dd6-87d7-191637ea5c5d",
            "sourceColumn": "Item",
            "summarizeBy": "none"
          },
          {
            "name": "N Libro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e96cdb1d-4903-4ba5-9b47-750e85afa21c",
            "sourceColumn": "N Libro",
            "summarizeBy": "none"
          },
          {
            "name": "Apertura Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "359b80a6-09ff-4adb-afa7-e959220d802e",
            "sourceColumn": "Apertura Indice",
            "summarizeBy": "none"
          },
          {
            "name": "Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e0047169-e73c-434f-bdb5-0ccb146bc3fd",
            "sourceColumn": "Indice",
            "summarizeBy": "none"
          },
          {
            "name": "Cruce Maestra",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "'Maestra Indice'[N Libro]&'Maestra Indice'[Apertura Indice]&'Maestra Indice'[Indice]",
            "isDataTypeInferred": true,
            "lineageTag": "f97d267f-6de5-42b1-b63d-9574d4de0847",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "8eefd616-4956-4394-8c1c-65f4871b7ded",
        "partitions": [
          {
            "name": "Maestra Indice-5e42d4d8-7936-4f17-9b36-20fd6d08f73e",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Excel.Workbook(Web.Contents(\"https://agrosuper.sharepoint.com/sites/GerenciaPlanificacion/BI/Documentos%20compartidos/Agristats/Maestra%20Indices.xlsx\"), null, true),",
                "    #\"Maestra Indice_Sheet\" = Origen{[Item=\"Maestra Indice\",Kind=\"Sheet\"]}[Data],",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Maestra Indice_Sheet\",{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}}),",
                "    #\"Encabezados promovidos\" = Table.PromoteHeaders(#\"Tipo cambiado\", [PromoteAllScalars=true]),",
                "    #\"Tipo cambiado1\" = Table.TransformColumnTypes(#\"Encabezados promovidos\",{{\"Sector\", type text}, {\"Item\", type text}, {\"N Libro\", type text}, {\"Apertura Indice\", type text}, {\"Indice\", type text}})",
                "in",
                "    #\"Tipo cambiado1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_ffcf9b00-c533-40ee-ad42-a445f492ded8",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c132c2c7-affd-4f46-814a-e18fe0082d50",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3dd86c32-6efb-49ea-86bb-fc6f072c8775",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3af72454-30b9-4832-9eee-0ac0c0adc65a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "69865068-db10-4dd6-bf34-a4e7e99ed687",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "cc8c66d5-4e0c-465d-a8e2-9153eee68612",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ed36e68a-8e18-4254-922a-0a9b2a1b5f0a",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c7754e1c-79ea-43bb-a308-6277d90d53a0",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "91b35926-abd3-41d0-9a67-ecab677fb77d",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "6df445fc-2828-4832-a80c-6dbd145683b9",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "bd2fa599-e709-4946-8586-192831c357ce",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "a5e30ec0-f27e-4028-b38d-03152bc38da1",
                "ordinal": 3
              }
            ],
            "lineageTag": "5f6fb47f-3fff-4623-b86f-530104d817bb"
          }
        ],
        "isHidden": true,
        "lineageTag": "0ed7dc5d-a21e-4cfe-84d4-ecbd27962589",
        "partitions": [
          {
            "name": "LocalDateTable_ffcf9b00-c533-40ee-ad42-a445f492ded8-b910c8c3-0988-41e8-afa5-9eadc7d7dd86",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Agristat live_mm_fact'[Fecha Libro])), 1, 1), Date(Year(MAX('Agristat live_mm_fact'[Fecha Libro])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Maestra Vivo",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Tipo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8decc4c0-2a72-4002-90c9-7e3f57a25796",
            "sourceColumn": "Tipo",
            "summarizeBy": "none"
          },
          {
            "name": "N° Libro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "42b3f256-3c0f-4df2-9ca6-7556e21aa1ce",
            "sourceColumn": "N° Libro",
            "summarizeBy": "none"
          },
          {
            "name": "Descripción Libro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "069b45e1-e96e-4490-afab-a9e7dd951a77",
            "sourceColumn": "Descripción Libro",
            "summarizeBy": "none"
          },
          {
            "name": "Cod. Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "097c7890-ee03-4264-b054-5c35cf0f5ed0",
            "sourceColumn": "Cod. Indice",
            "summarizeBy": "none"
          },
          {
            "name": "Descripción Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "48f6bd09-946a-4f10-84d1-6edaa39ac454",
            "sourceColumn": "Descripción Indice",
            "summarizeBy": "none"
          },
          {
            "name": "Apertura Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc0153c4-82c8-493e-8ebe-1bc3f5219fc4",
            "sourceColumn": "Apertura Indice",
            "summarizeBy": "none"
          },
          {
            "name": "Descripción Apertura Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f382fe51-93f5-45a7-81b9-9491f7480717",
            "sourceColumn": "Descripción Apertura Indice",
            "summarizeBy": "none"
          },
          {
            "name": "Cruce Maestra Vivo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "'Maestra Vivo'[Sector]&'Maestra Vivo'[N° Libro]&'Maestra Vivo'[Cod. Indice]&'Maestra Vivo'[Apertura Indice]",
            "isDataTypeInferred": true,
            "lineageTag": "acaed689-a444-49f4-9648-8a20a0882b76",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Indice AS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "'Maestra Vivo'[Apertura Indice]&\" - \"&'Maestra Vivo'[Descripción Apertura Indice]",
            "isDataTypeInferred": true,
            "lineageTag": "ceb49a81-fb34-4581-9732-fe9397fa8c15",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Sector",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "35d1f3e8-bd84-4000-9864-b72709f21d92",
            "sourceColumn": "Sector",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "10eca6d9-0be3-4702-9605-398f644ee137",
        "partitions": [
          {
            "name": "Maestra Vivo-2fabf27a-ac9e-4e9b-b184-e87c0ea4c908",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Excel.Workbook(Web.Contents(\"https://agrosuper.sharepoint.com/sites/GerenciaPlanificacion/BI/Documentos%20compartidos/Agristats/Automatizaci%C3%B3n%20Agristats/Producci%C3%B3n%20Animal/Maestra%20Vivo.xlsx\"), null, true),",
                "    #\"Maestra Vivo_Sheet\" = Origen{[Item=\"Maestra Vivo\",Kind=\"Sheet\"]}[Data],",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Maestra Vivo_Sheet\",{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}, {\"Column6\", type text}, {\"Column7\", type text}}),",
                "    #\"Encabezados promovidos\" = Table.PromoteHeaders(#\"Tipo cambiado\", [PromoteAllScalars=true]),",
                "    #\"Tipo cambiado1\" = Table.TransformColumnTypes(#\"Encabezados promovidos\",{{\"Tipo\", type text}, {\"N° Libro\", type text}, {\"Descripción Libro\", type text}, {\"Cod. Indice\", type text}, {\"Descripción Indice\", type text}, {\"Apertura Indice\", type text}, {\"Descripción Apertura Indice\", type text}})",
                "in",
                "    #\"Tipo cambiado1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dólar Banco central",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          }
        ],
        "columns": [
          {
            "name": "Serie",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb5e3e79-3012-4345-b203-b8bf22786955",
            "sourceColumn": "Serie",
            "summarizeBy": "none"
          },
          {
            "name": "Periodo Dólar",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "1fd4c5ee-859f-4050-a9d6-480ec772f674",
            "sourceColumn": "Periodo Dólar",
            "summarizeBy": "none"
          },
          {
            "name": "Dólar",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb3c7d9e-8bfd-488c-a8a0-1c7acba279f7",
            "sourceColumn": "Dólar",
            "summarizeBy": "none"
          },
          {
            "name": "Dólar AA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a6e0fecb-097b-49ef-90dd-6384317dfa09",
            "sourceColumn": "Dólar AA",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bca2dcee-3e4f-45f5-8707-554e13ccd46d",
        "partitions": [
          {
            "name": "Dólar Banco central-a8c52475-7f11-4910-8ab3-8344e71e09a5",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Web.Page(Web.Contents(\"https://si3.bcentral.cl/siete/ES/Siete/Cuadro/CAP_TIPO_CAMBIO/MN_TIPO_CAMBIO4/DOLAR_OBS_ADO?cbFechaInicio=2021&cbFechaTermino=2023&cbFrecuencia=MONTHLY&cbCalculo=NONE&cbFechaBase=\")),",
                "    Data = Origen{0}[Data],",
                "    #\"Otras columnas con anulación de dinamización\" = Table.UnpivotOtherColumns(Data, {\"Serie\"}, \"Atributo\", \"Valor\"),",
                "    #\"Filas filtradas\" = Table.SelectRows(#\"Otras columnas con anulación de dinamización\", each ([Atributo] <> \"Sel.\")),",
                "    #\"Consulta anexada\" = Table.Combine({#\"Filas filtradas\", #\"Dólar Banco central 2018 a 2020\"}),",
                "    #\"Tipo cambiado2\" = Table.TransformColumnTypes(#\"Consulta anexada\",{{\"Atributo\", type date}}),",
                "    #\"Filas ordenadas\" = Table.Sort(#\"Tipo cambiado2\",{{\"Atributo\", Order.Ascending}}),",
                "    #\"Columnas con nombre cambiado\" = Table.RenameColumns(#\"Filas ordenadas\",{{\"Atributo\", \"Periodo Dólar\"}, {\"Valor\", \"Dólar\"}}),",
                "    #\"Consultas combinadas\" = Table.NestedJoin(#\"Columnas con nombre cambiado\", {\"Periodo Dólar\"}, #\"Dólar Banco central AA\", {\"Periodo Dólar AA\"}, \"Dólar Banco central AA\", JoinKind.LeftOuter),",
                "    #\"Se expandió Dólar Banco central AA\" = Table.ExpandTableColumn(#\"Consultas combinadas\", \"Dólar Banco central AA\", {\"Dólar AA\"}, {\"Dólar AA\"})",
                "in",
                "    #\"Se expandió Dólar Banco central AA\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Agristat lot_mult_mm_fact",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "lot_mult_mm_fact_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2bee9a09-9ce1-4c26-b901-5c568291533f",
            "sourceColumn": "lot_mult_mm_fact_id",
            "summarizeBy": "none"
          },
          {
            "name": "strt_mm_tm_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ddaaca95-d30b-4c23-952c-e2090c5e6293",
            "sourceColumn": "strt_mm_tm_id",
            "summarizeBy": "none"
          },
          {
            "name": "end_mm_tm_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d1e5c592-1296-4eed-9f9a-9c3c85b69885",
            "sourceColumn": "end_mm_tm_id",
            "summarizeBy": "none"
          },
          {
            "name": "run_grp_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8e1d7dcc-cf92-444c-b043-85682da0092e",
            "sourceColumn": "run_grp_id",
            "summarizeBy": "none"
          },
          {
            "name": "clmn_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "48dab3e6-3792-4def-bbcb-b503d651157a",
            "sourceColumn": "clmn_id",
            "summarizeBy": "none"
          },
          {
            "name": "line_grp_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4426bd2d-1318-4080-a168-5e7bed165ea6",
            "sourceColumn": "line_grp_cd",
            "summarizeBy": "none"
          },
          {
            "name": "Cod. Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bda730cd-64a0-470d-b863-3e110e868e6a",
            "sourceColumn": "Cod. Indice",
            "summarizeBy": "none"
          },
          {
            "name": "Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c85a4f3e-a20f-4bc6-b324-ba1e9fde635d",
            "sourceColumn": "Indice",
            "summarizeBy": "none"
          },
          {
            "name": "nmrc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cc51ac57-1562-4a4a-a66b-519eb9f78dee",
            "sourceColumn": "nmrc",
            "summarizeBy": "sum"
          },
          {
            "name": "charval",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a5eebf36-6b31-4985-94a7-87698bada3ce",
            "sourceColumn": "charval",
            "summarizeBy": "none"
          },
          {
            "name": "lot",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a0b1fe0e-4962-4a1d-bd0a-9b2e137449a3",
            "sourceColumn": "lot",
            "summarizeBy": "none"
          },
          {
            "name": "flow_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "575ee406-1767-4218-b5ae-e447878b094d",
            "sourceColumn": "flow_id",
            "summarizeBy": "none"
          },
          {
            "name": "flow_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "52640f6f-a589-467a-af6e-fc487e9e406c",
            "sourceColumn": "flow_nm",
            "summarizeBy": "none"
          },
          {
            "name": "last_db_updt_ts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "32c6e38a-4c60-407c-8c4a-0345bb5fdc07",
            "sourceColumn": "last_db_updt_ts",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variación",
                "defaultHierarchy": {
                  "hierarchy": "Jerarquía de fechas",
                  "table": "LocalDateTable_1159a0d0-a5d5-4120-beae-43967ef541ef"
                },
                "isDefault": true,
                "relationship": "325147df-dd6a-49a1-996d-ce5df1736e46"
              }
            ]
          },
          {
            "name": "fact_type_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "adb55464-c5a2-4597-8d37-e0af6df09a0c",
            "sourceColumn": "fact_type_cd",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "91fa94e4-fe29-4cd1-a3ad-323ea3713255",
        "partitions": [
          {
            "name": "Agristat lot_mult_mm_fact-9a54ce37-cd0d-4f5d-8189-1687085ed4ba",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Sql.Database(\"10.195.4.4\", \"sqldb-as-gplanificacionygestion-pyg-prd\"),",
                "    Agristat_live_mm_fact = Origen{[Schema=\"Agristat\",Item=\"lot_mult_mm_fact_hist\"]}[Data],",
                "    #\"Columnas con nombre cambiado\" = Table.RenameColumns(Agristat_live_mm_fact,{{\"fact_dsc_nm\", \"Indice\"}, {\"fact_dsc_cd\", \"Cod. Indice\"}})",
                "in",
                "    #\"Columnas con nombre cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_1159a0d0-a5d5-4120-beae-43967ef541ef",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "32043869-111e-474c-8751-4fe6d4880edc",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "090cb0bb-fc74-4531-9769-098003603d33",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "809c41ec-806f-4023-b739-47d4042c9269",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "725e171d-5f12-483b-bc04-06e36dc9a8bb",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "11be3c8f-539d-4aed-9e05-9812351e1b8a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "fa349302-7093-444d-9488-7905adc000bd",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "67d7b085-d05f-49a4-9be2-f9f515663dd5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "ce637a9a-5454-47f4-b5fe-f84b6553bf73",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "d1c6585d-501d-43b3-8b61-691f67091325",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "0376eab3-bf13-4aa9-8ab6-9d496ddee70a",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "963ea7df-f4c7-4adb-b815-2982463da9da",
                "ordinal": 3
              }
            ],
            "lineageTag": "70ba2213-b0d8-47d3-95a4-1d9d2c0ff4ec"
          }
        ],
        "isHidden": true,
        "lineageTag": "1a254fc5-d55c-41b1-b329-bcc9f5b94c6f",
        "partitions": [
          {
            "name": "LocalDateTable_1159a0d0-a5d5-4120-beae-43967ef541ef-323dcc2d-f1ed-4eb7-9f9e-1dd310e9877f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Agristat lot_mult_mm_fact'[last_db_updt_ts])), 1, 1), Date(Year(MAX('Agristat lot_mult_mm_fact'[last_db_updt_ts])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_5206c8d1-fae5-46d0-97a0-f8e6aa8331a8",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6d9cb5fb-fe5d-4c0b-b43c-797a05df327b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a0585daa-52c2-464d-b829-66360cb72b08",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8903ff8b-c2ef-48ef-ab70-f845a022ecc2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "412b8e43-b5fc-4d6c-8fed-1ac4b7256e87",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0be475b0-5c28-4724-947c-35a3a48db7e7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ffaa6f85-7fb4-40a2-8f70-a1d413bd6c9a",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "27a4a535-5ffd-41ff-aaaa-2af3556cfc2a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "1e0ebf56-f611-417c-a113-f831e4ea28b2",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "8375608e-8b11-47b4-bc9e-16d7663137ea",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "81143a85-1e68-4b8e-b938-7df14e47192c",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "459477a9-354a-4d5e-8c2b-12b116f5756b",
                "ordinal": 3
              }
            ],
            "lineageTag": "dad474c3-c48e-4ea3-baeb-9f935fb1809a"
          }
        ],
        "isHidden": true,
        "lineageTag": "16a06579-b109-45e8-92a1-f6506c9fb6bc",
        "partitions": [
          {
            "name": "LocalDateTable_5206c8d1-fae5-46d0-97a0-f8e6aa8331a8-fc1bb423-73fb-4ea6-83bd-df5f152e3bcc",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Agristat live_mm_fact'[Fecha Libro - 6 Meses])), 1, 1), Date(Year(MAX('Agristat live_mm_fact'[Fecha Libro - 6 Meses])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Filtro Comparación",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Comparación",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "ac838a71-81c0-4831-a5bd-add77ff99c9d",
            "sortByColumn": "Orden",
            "sourceColumn": "Comparación",
            "summarizeBy": "none"
          },
          {
            "name": "Orden",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bc453283-24ab-4d9c-93f2-fa6223969567",
            "sourceColumn": "Orden",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "9c1dc145-942e-4bf4-88e1-b24e2924c9e9",
        "partitions": [
          {
            "name": "Filtro Comparación-25eade41-63dd-4566-b01c-6c9f47f1d197",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCs0p0VMwVshNLU4tVtJRMlKK1YEKmsEFjRGChkZwUROwqG9qsYJjXklqUWZ+EVDQUCk2FgA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t, Columna2 = _t]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(Origen,{{\"Columna1\", type text}, {\"Columna2\", Int64.Type}}),",
                "    #\"Columnas con nombre cambiado\" = Table.RenameColumns(#\"Tipo cambiado\",{{\"Columna1\", \"Comparación\"}, {\"Columna2\", \"Orden\"}})",
                "in",
                "    #\"Columnas con nombre cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Filtro Cascada",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Filtro Cascada",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc34cd7d-f10b-4345-918a-83af98ebbb2e",
            "sortByColumn": "ID",
            "sourceColumn": "Filtro Cascada",
            "summarizeBy": "none"
          },
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d116d13f-ab8d-4aa3-bf8e-4a88f26202c9",
            "sourceColumn": "ID",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "a457c406-fc6c-4e93-9bc6-fad001de67ab",
        "partitions": [
          {
            "name": "Filtro Cascada-56614081-724d-497a-9b81-4699b383c178",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCs0p0VPwTS1W0lEyUorViVYKKMrP1VOACYMlDJViYwE=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t, Columna2 = _t]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(Origen,{{\"Columna1\", type text}, {\"Columna2\", Int64.Type}}),",
                "    #\"Columnas con nombre cambiado\" = Table.RenameColumns(#\"Tipo cambiado\",{{\"Columna1\", \"Filtro Cascada\"}, {\"Columna2\", \"ID\"}})",
                "in",
                "    #\"Columnas con nombre cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Agristat live_mm_fact AGROSUPER AA",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "live_mm_fact_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2f166ed0-0436-4c4e-9f5d-3dbb571c1eb4",
            "sourceColumn": "live_mm_fact_id",
            "summarizeBy": "sum"
          },
          {
            "name": "run_grp_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d244a6e2-3d9b-44e0-85c4-c1c9e4706c51",
            "sourceColumn": "run_grp_id",
            "summarizeBy": "sum"
          },
          {
            "name": "clmn_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "45baf989-ec0d-4e18-a071-094f11c8cd72",
            "sourceColumn": "clmn_id",
            "summarizeBy": "sum"
          },
          {
            "name": "line_grp_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "62e8a7ac-4a5c-4585-8762-e8aff803e638",
            "sourceColumn": "line_grp_cd",
            "summarizeBy": "none"
          },
          {
            "name": "Cod. Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc3bc1bc-a5fb-426c-b6eb-a5f8d0ae19a6",
            "sourceColumn": "Cod. Indice",
            "summarizeBy": "none"
          },
          {
            "name": "nmrc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9e430216-43fd-4245-8cf0-63c0a614bd4d",
            "sourceColumn": "nmrc",
            "summarizeBy": "sum"
          },
          {
            "name": "charval",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "450a11ae-3e63-41f0-8770-a4c108b33ad3",
            "sourceColumn": "charval",
            "summarizeBy": "none"
          },
          {
            "name": "last_db_updt_ts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "2ab565df-cdcc-424d-961d-13e5462fe2f4",
            "sourceColumn": "last_db_updt_ts",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variación",
                "defaultHierarchy": {
                  "hierarchy": "Jerarquía de fechas",
                  "table": "LocalDateTable_a3902b18-2e54-4675-9228-ed0df837ebf8"
                },
                "isDefault": true,
                "relationship": "c0023206-4460-4d6c-92e5-1f381169cbc6"
              }
            ]
          },
          {
            "name": "fact_type_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f25fb5db-2c97-467c-bc19-627ede8bc23c",
            "sourceColumn": "fact_type_cd",
            "summarizeBy": "none"
          },
          {
            "name": "Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d322a9be-cecb-45f7-a78c-55a82baecf1b",
            "sourceColumn": "Indice",
            "summarizeBy": "none"
          },
          {
            "name": "mm_tm_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "03e8d19f-cc28-41a4-be98-e09200036883",
            "sourceColumn": "mm_tm_id",
            "summarizeBy": "sum"
          },
          {
            "name": "mm_tm_id.1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "56a514d4-4edb-4e19-8578-3312548f7d89",
            "sourceColumn": "mm_tm_id.1",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "574eaba3-2668-4027-bb8e-e4e781c4c3d2",
        "partitions": [
          {
            "name": "Agristat live_mm_fact AGROSUPER AA-5c049246-2494-4c61-8085-ed5123c339c2",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Sql.Database(\"10.195.4.4\", \"sqldb-as-gplanificacionygestion-pyg-prd\"),",
                "    Agristat_live_mm_fact = Origen{[Schema=\"Agristat\",Item=\"live_mm_fact_hist\"]}[Data],",
                "    #\"Columnas con nombre cambiado\" = Table.RenameColumns(Agristat_live_mm_fact,{{\"fact_dsc_nm\", \"Indice\"}, {\"fact_dsc_cd\", \"Cod. Indice\"}}),",
                "    #\"Filas filtradas\" = Table.SelectRows(#\"Columnas con nombre cambiado\", each ([Indice] = \"AGROSUPER\" or [Indice] = \"AGROSUPER - CONDENSADO\" or [Indice] = \"AGROSUPER 1 RANCAGUA, CHILE\" or [Indice] = \"AGROSUPER 2 RANCAGUA, CHILE\" or [Indice] = \"AGROSUPER 3 RANCAGUA, CHILE\" or [Indice] = \"AGROSUPER 4 RANCAGUA, CHILE\" or [Indice] = \"AGROSUPER 5 RANCAGUA, CHILE\" or [Indice] = \"AGROSUPER 6 RANCAGUA, CHILE\" or [Indice] = \"AGROSUPER MISTO TR\" or [Indice] = \"AGROSUPER S.A.\" or [Indice] = \"Other than AGROSUPER\" or [Indice] = \"Other than AGROSUPER - CONDENSADO\" or [Indice] = \"Other than AGROSUPER S.A.\")),",
                "    #\"Columnas con nombre cambiado1\" = Table.RenameColumns(#\"Filas filtradas\",{{\"Indice\", \"Indice Original\"}}),",
                "    #\"Personalizada agregada\" = Table.AddColumn(#\"Columnas con nombre cambiado1\", \"Indice\", each [Indice Original]&\" AA\"),",
                "    #\"Columnas con nombre cambiado2\" = Table.RenameColumns(#\"Personalizada agregada\",{{\"mm_tm_id\", \"mm_tm_id Original\"}}),",
                "    #\"Personalizada agregada1\" = Table.AddColumn(#\"Columnas con nombre cambiado2\", \"mm_tm_id\", each [mm_tm_id Original]+12),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Personalizada agregada1\",{{\"Indice\", type text}, {\"mm_tm_id\", Int64.Type}}),",
                "    #\"Columnas quitadas\" = Table.RemoveColumns(#\"Tipo cambiado\",{\"mm_tm_id Original\", \"Indice Original\"}),",
                "    #\"Consultas combinadas\" = Table.NestedJoin(#\"Columnas quitadas\", {\"mm_tm_id\"}, #\"Fechas de libros en SQL\", {\"mm_tm_id\"}, \"Fechas de libros en SQL\", JoinKind.LeftOuter),",
                "    #\"Se expandió Fechas de libros en SQL\" = Table.ExpandTableColumn(#\"Consultas combinadas\", \"Fechas de libros en SQL\", {\"mm_tm_id\"}, {\"mm_tm_id.1\"}),",
                "    #\"Filas filtradas1\" = Table.SelectRows(#\"Se expandió Fechas de libros en SQL\", each [mm_tm_id.1] <> null)",
                "in",
                "    #\"Filas filtradas1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_a3902b18-2e54-4675-9228-ed0df837ebf8",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a742f616-a6c2-4a03-86c9-fdae6a93d1e0",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3bc1070c-acb6-4bb2-88d5-8dd4ad998373",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5f503833-6133-484a-9de6-499af19edd06",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b0212bba-5cf3-4b15-8898-2d2d6fa01513",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1d0c49f9-6fc5-4bec-9ab1-c59ff5ff5409",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2e773c77-ee13-47ff-ba59-d2d8c974cf46",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a326023b-7fcd-4fe3-8531-840fd1c7410d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "65dc55a5-8642-474f-874c-25f4ee68427c",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "1760653e-9816-48ab-ac03-1a409b02d56f",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "ef21b4b2-b008-4c61-83fa-a7954acbaac8",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "75f98299-4929-46ff-876a-5192e5192b63",
                "ordinal": 3
              }
            ],
            "lineageTag": "1cb12b5f-8d86-49c2-b306-e3bac2835d25"
          }
        ],
        "isHidden": true,
        "lineageTag": "7b2e2527-8cd8-410a-9ee1-0fb3cd1e40b0",
        "partitions": [
          {
            "name": "LocalDateTable_a3902b18-2e54-4675-9228-ed0df837ebf8-c8ef6fe6-9fe9-4e4e-a12c-f6e2fa653119",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Agristat live_mm_fact AGROSUPER AA'[last_db_updt_ts])), 1, 1), Date(Year(MAX('Agristat live_mm_fact AGROSUPER AA'[last_db_updt_ts])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Fechas de libros en SQL",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "mm_tm_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "57900880-205b-45d7-bb10-983f0761c236",
            "sourceColumn": "mm_tm_id",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "d4be1309-1c20-4d71-b222-f3592bc9d1bb",
        "partitions": [
          {
            "name": "Fechas de libros en SQL-662455f5-bbfe-418e-afa8-32f79d7f422d",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Sql.Database(\"10.195.4.4\", \"sqldb-as-gplanificacionygestion-pyg-prd\", [Query=\"SELECT [mm_tm_id] FROM [Agristat].[live_mm_fact_hist] group by [mm_tm_id]\"])",
                "in",
                "    Origen"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dólar Banco central AA",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          }
        ],
        "columns": [
          {
            "name": "Serie",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2818f247-bb30-48c4-8f91-734e8c0972ce",
            "sourceColumn": "Serie",
            "summarizeBy": "none"
          },
          {
            "name": "Dólar AA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "76d8e88d-fc4f-4d7b-b1eb-102ea1ff33aa",
            "sourceColumn": "Dólar AA",
            "summarizeBy": "none"
          },
          {
            "name": "Periodo Dólar AA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "760aa12f-84f0-4993-9d11-b1577528d9dd",
            "sourceColumn": "Periodo Dólar AA",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variación",
                "defaultHierarchy": {
                  "hierarchy": "Jerarquía de fechas",
                  "table": "LocalDateTable_7270bf4c-a9ee-4fa3-9bac-ec22171551da"
                },
                "isDefault": true,
                "relationship": "c296cb80-5a91-472b-95aa-f36f1f4c28cf"
              }
            ]
          }
        ],
        "lineageTag": "951fe7df-44cd-4a16-a0eb-4b372c397a49",
        "partitions": [
          {
            "name": "Dólar Banco central AA-30c87086-4d69-418c-9406-1c83a6231f10",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Web.Page(Web.Contents(\"https://si3.bcentral.cl/siete/ES/Siete/Cuadro/CAP_TIPO_CAMBIO/MN_TIPO_CAMBIO4/DOLAR_OBS_ADO?cbFechaInicio=2021&cbFechaTermino=2023&cbFrecuencia=MONTHLY&cbCalculo=NONE&cbFechaBase=\")),",
                "    Data = Origen{0}[Data],",
                "    #\"Otras columnas con anulación de dinamización\" = Table.UnpivotOtherColumns(Data, {\"Serie\"}, \"Atributo\", \"Valor\"),",
                "    #\"Filas filtradas\" = Table.SelectRows(#\"Otras columnas con anulación de dinamización\", each ([Atributo] <> \"Sel.\")),",
                "    #\"Tipo cambiado2\" = Table.TransformColumnTypes(#\"Filas filtradas\",{{\"Atributo\", type date}}),",
                "    #\"Columnas con nombre cambiado\" = Table.RenameColumns(#\"Tipo cambiado2\",{{\"Atributo\", \"Periodo Dólar\"}, {\"Valor\", \"Dólar\"}}),",
                "    #\"Personalizada agregada\" = Table.AddColumn(#\"Columnas con nombre cambiado\", \"Periodo Dólar AA\", each Date.AddYears([Periodo Dólar],1)),",
                "    #\"Columnas con nombre cambiado1\" = Table.RenameColumns(#\"Personalizada agregada\",{{\"Dólar\", \"Dólar AA\"}}),",
                "    #\"Tipo cambiado3\" = Table.TransformColumnTypes(#\"Columnas con nombre cambiado1\",{{\"Periodo Dólar AA\", type date}}),",
                "    #\"Columnas quitadas1\" = Table.RemoveColumns(#\"Tipo cambiado3\",{\"Periodo Dólar\"}),",
                "    #\"Consulta anexada\" = Table.Combine({#\"Columnas quitadas1\", #\"Dólar Banco central AA 2017 - 2020\"})",
                "in",
                "    #\"Consulta anexada\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_7270bf4c-a9ee-4fa3-9bac-ec22171551da",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2a8b2f23-8808-4dca-8ac8-1f513c73090c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a320f2e1-89f3-456c-9903-24f39e97d61e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "dd592d00-241a-4b43-987e-7937dd5c7b3a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "87121828-9f67-4ff6-8c3f-1c9766778f4e",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "bfa3b998-ba2d-4dca-b8ca-8400736ea521",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ac792749-297d-43f9-93e5-34ea356b277f",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "fd5e91bc-9f01-436a-8ace-4f3d7adefc25",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "c187df59-1b55-4a41-82e5-dcd47e977f9d",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "9408830f-0dd8-4ece-8638-3d0000cf543c",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "3e3fb89e-af03-41e1-badc-4287f2c7f7e8",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "ee1d92de-34b5-4489-a6c8-c39c787ba7b7",
                "ordinal": 3
              }
            ],
            "lineageTag": "67198aa7-69b6-4708-bab1-3b88e21ca7fe"
          }
        ],
        "isHidden": true,
        "lineageTag": "a2ff3419-ae0c-4933-9bf9-832fb3acb020",
        "partitions": [
          {
            "name": "LocalDateTable_7270bf4c-a9ee-4fa3-9bac-ec22171551da-745c81f1-4a05-4bde-87fe-4ad855699030",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Dólar Banco central AA'[Periodo Dólar AA])), 1, 1), Date(Year(MAX('Dólar Banco central AA'[Periodo Dólar AA])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Dólar Banco central 2018 a 2020",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          }
        ],
        "columns": [
          {
            "name": "Serie",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a3d11eb9-efc4-40bf-a0db-8af154e3a6a8",
            "sourceColumn": "Serie",
            "summarizeBy": "none"
          },
          {
            "name": "Atributo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9c64fe3e-eb06-43c6-97fe-faa6a2421493",
            "sourceColumn": "Atributo",
            "summarizeBy": "none"
          },
          {
            "name": "Valor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0af1138d-8a10-4eda-ae5f-4cfe654e75db",
            "sourceColumn": "Valor",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "eb24094c-2b49-452e-ac90-6f9dcc0dc8f8",
        "partitions": [
          {
            "name": "Dólar Banco central 2018 a 2020-8a1dbe40-0065-4a45-9d49-2f658f4f0538",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen =  Web.Page(Web.Contents(\"https://si3.bcentral.cl/siete/ES/Siete/Cuadro/CAP_TIPO_CAMBIO/MN_TIPO_CAMBIO4/DOLAR_OBS_ADO?cbFechaInicio=2018&cbFechaTermino=2020&cbFrecuencia=MONTHLY&cbCalculo=NONE&cbFechaBase=\")),",
                "    Data = Origen{0}[Data],",
                "    #\"Otras columnas con anulación de dinamización\" = Table.UnpivotOtherColumns(Data, {\"Serie\"}, \"Atributo\", \"Valor\"),",
                "    #\"Filas filtradas\" = Table.SelectRows(#\"Otras columnas con anulación de dinamización\", each ([Atributo] <> \"Sel.\"))",
                "in",
                "    #\"Filas filtradas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dólar Banco central AA 2017 - 2020",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          }
        ],
        "columns": [
          {
            "name": "Serie",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "385c529d-1530-4c69-97ae-d0d120a704da",
            "sourceColumn": "Serie",
            "summarizeBy": "none"
          },
          {
            "name": "Dólar AA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4583b9c3-05d8-4d4b-8917-0e3429a175e8",
            "sourceColumn": "Dólar AA",
            "summarizeBy": "none"
          },
          {
            "name": "Periodo Dólar AA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "e38f8d02-9a12-4353-a1e9-7bb0aa08bb93",
            "sourceColumn": "Periodo Dólar AA",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variación",
                "defaultHierarchy": {
                  "hierarchy": "Jerarquía de fechas",
                  "table": "LocalDateTable_fc00b6af-6425-4eaa-80ff-02b5a458d05b"
                },
                "isDefault": true,
                "relationship": "2e7ef3bb-e14a-4fd0-82df-c30c7adf071f"
              }
            ]
          }
        ],
        "lineageTag": "0b10d905-bb83-4657-a620-c545df424da6",
        "partitions": [
          {
            "name": "Dólar Banco central AA 2017 - 2020-53c83bbf-82e2-4528-8fd8-46d6141333b6",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Web.Page(Web.Contents(\"https://si3.bcentral.cl/siete/ES/Siete/Cuadro/CAP_TIPO_CAMBIO/MN_TIPO_CAMBIO4/DOLAR_OBS_ADO?cbFechaInicio=2017&cbFechaTermino=2020&cbFrecuencia=MONTHLY&cbCalculo=NONE&cbFechaBase=\")),",
                "    Data = Origen{0}[Data],",
                "    #\"Otras columnas con anulación de dinamización\" = Table.UnpivotOtherColumns(Data, {\"Serie\"}, \"Atributo\", \"Valor\"),",
                "    #\"Filas filtradas\" = Table.SelectRows(#\"Otras columnas con anulación de dinamización\", each ([Atributo] <> \"Sel.\")),",
                "    #\"Tipo cambiado2\" = Table.TransformColumnTypes(#\"Filas filtradas\",{{\"Atributo\", type date}}),",
                "    #\"Columnas con nombre cambiado\" = Table.RenameColumns(#\"Tipo cambiado2\",{{\"Atributo\", \"Periodo Dólar\"}, {\"Valor\", \"Dólar\"}}),",
                "    #\"Personalizada agregada\" = Table.AddColumn(#\"Columnas con nombre cambiado\", \"Periodo Dólar AA\", each Date.AddYears([Periodo Dólar],1)),",
                "    #\"Columnas con nombre cambiado1\" = Table.RenameColumns(#\"Personalizada agregada\",{{\"Dólar\", \"Dólar AA\"}}),",
                "    #\"Tipo cambiado3\" = Table.TransformColumnTypes(#\"Columnas con nombre cambiado1\",{{\"Periodo Dólar AA\", type date}}),",
                "    #\"Columnas quitadas1\" = Table.RemoveColumns(#\"Tipo cambiado3\",{\"Periodo Dólar\"})",
                "in",
                "    #\"Columnas quitadas1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_fc00b6af-6425-4eaa-80ff-02b5a458d05b",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "fd964d10-5637-4c53-9099-587c6c39bd69",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2694626d-8b68-40dd-8909-55750c26c7a0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8952314a-775d-4946-88b8-7524d6392de4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3f732701-b6b4-4898-8180-0f6ee2259c89",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "027c4fd1-df32-4e4d-b984-280faa37c0fa",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "cefe1b4a-9e9d-4100-9988-3d18010ac292",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8386d01d-9a47-4469-9c71-b324320ee394",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "a9d2fd99-aaa8-40d6-9fa6-0992076ced86",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "80c16122-fae0-4490-ba77-733764cc32b7",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "7653eb72-42f3-4144-ae15-250cb0d5948d",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "4d2cada7-6728-4953-8e08-bdc782ef0c9d",
                "ordinal": 3
              }
            ],
            "lineageTag": "8a72cf90-0618-4887-b1c5-0cc24a1f7aab"
          }
        ],
        "isHidden": true,
        "lineageTag": "cd61706b-0622-447b-9ee8-c20ae6fe105b",
        "partitions": [
          {
            "name": "LocalDateTable_fc00b6af-6425-4eaa-80ff-02b5a458d05b-a58060bb-7aae-4263-937d-45bb319d43d1",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Dólar Banco central AA 2017 - 2020'[Periodo Dólar AA])), 1, 1), Date(Year(MAX('Dólar Banco central AA 2017 - 2020'[Periodo Dólar AA])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Maestra Industrial",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "sys_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "28e40a4f-1c35-4e57-a3fd-79cd453f7c1b",
            "sourceColumn": "sys_cd",
            "summarizeBy": "none"
          },
          {
            "name": "Sector",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "22275dd4-00ad-4603-a251-657c25a5876b",
            "sourceColumn": "Sector",
            "summarizeBy": "none"
          },
          {
            "name": "N Libro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e517f38a-984d-4f28-8d88-facbe980514b",
            "sourceColumn": "N Libro",
            "summarizeBy": "none"
          },
          {
            "name": "Descripción Libro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d1e8927-51be-44f1-9385-87d7e3f96960",
            "sourceColumn": "Descripción Libro",
            "summarizeBy": "none"
          },
          {
            "name": "Apertura Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ff9eb3ac-d32f-4e88-8b30-9b16879572c3",
            "sourceColumn": "Apertura Indice",
            "summarizeBy": "none"
          },
          {
            "name": "Desc Apertura Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Maestra Industrial\",\"TableItemName\":\"Desc Apertura Indice (grupos)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "string",
            "lineageTag": "b94abd5d-4870-4332-a48b-1bf7a25e90dd",
            "sourceColumn": "Desc Apertura Indice",
            "summarizeBy": "none"
          },
          {
            "name": "Cod. Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b936b220-4c55-44a4-8fc4-cb65ee0f936c",
            "sourceColumn": "Cod. Indice",
            "summarizeBy": "none"
          },
          {
            "name": "Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "497a3dac-ba6b-4036-96df-947923ee8692",
            "sortByColumn": "Orden Indice",
            "sourceColumn": "Indice",
            "summarizeBy": "none"
          },
          {
            "name": "Cruce Maestra Industrial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "'Maestra Industrial'[sys_cd]&'Maestra Industrial'[Sector]&'Maestra Industrial'[N Libro]&'Maestra Industrial'[Apertura Indice]&'Maestra Industrial'[Cod. Indice]",
            "isDataTypeInferred": true,
            "lineageTag": "04b4f70a-47da-4b3a-98e3-b4665c61c44f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Orden Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "RELATED(OrdenIndice[Orden Indice])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "d456bdb2-0420-4103-8de9-d0d08b362f04",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Desc Apertura Indice (grupos)",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"m\",\"Entity\":\"Maestra Industrial\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"m\"}},\"Property\":\"Desc Apertura Indice\"}}],\"GroupItems\":[{\"DisplayName\":\"(En blanco)\",\"BlankDefaultPlaceholder\":true},{\"DisplayName\":\"% de Vivo-Espinazo\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"m\"}},\"Property\":\"Desc Apertura Indice\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'% de Vivo-Espinazo Frontal'\"}}],[{\"Literal\":{\"Value\":\"'% de Vivo-Espinazo Trasero'\"}}]]}}}]}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "SWITCH(",
              "  TRUE,",
              "  ISBLANK('Maestra Industrial'[Desc Apertura Indice]),",
              "  \"(En blanco)\",",
              "  'Maestra Industrial'[Desc Apertura Indice] IN {\"% de Vivo-Espinazo Frontal\",",
              "    \"% de Vivo-Espinazo Trasero\"},",
              "  \"% de Vivo-Espinazo\",",
              "  'Maestra Industrial'[Desc Apertura Indice]",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "Maestra Industrial"
                          }
                        },
                        "Property": "Desc Apertura Indice"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "lineageTag": "0b2a37cb-19ba-4382-afda-6298fe281916",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "d002d7d6-1fa1-4340-b37e-110b7b62521c",
        "partitions": [
          {
            "name": "Maestra Industrial-1ea5465a-fb75-440c-b45d-861d0b6fa2a3",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Excel.Workbook(Web.Contents(\"https://agrosuper.sharepoint.com/sites/GerenciaPlanificacion/BI/Documentos%20compartidos/Agristats/Automatizaci%C3%B3n%20Agristats/Industrial/Maestra%20Industrial.xlsx\"), null, true),",
                "    #\"Maestra Industrial_Sheet\" = Origen{[Item=\"Maestra Industrial\",Kind=\"Sheet\"]}[Data],",
                "    #\"Encabezados promovidos\" = Table.PromoteHeaders(#\"Maestra Industrial_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Encabezados promovidos\",{{\"sys_cd\", type text}, {\"Sector\", type text}, {\"N Libro\", type text}, {\"Descripción Libro\", type text}, {\"Apertura Indice\", type text}, {\"Desc Apertura Indice\", type text}, {\"Cod. Indice\", type text}, {\"Indice\", type text}})",
                "in",
                "    #\"Tipo cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Usuario",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Usuario",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a59b2a0-bf9f-401b-ac10-dfd974665273",
            "sourceColumn": "Usuario",
            "summarizeBy": "none"
          },
          {
            "name": "Rol Prod. Animal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "872863b7-b59b-47df-8f7f-fcece74c0238",
            "sourceColumn": "Rol Prod. Animal",
            "summarizeBy": "none"
          },
          {
            "name": "Rol Industrial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "68527315-cde4-4b3f-8df4-cf4175d0fc7d",
            "sourceColumn": "Rol Industrial",
            "summarizeBy": "none"
          },
          {
            "name": "Prod. Animal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8dfa69b6-a2cf-41e9-bd28-70ffa6058f4c",
            "sourceColumn": "Prod. Animal",
            "summarizeBy": "none"
          },
          {
            "name": "Industrial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b8242590-b689-4bc3-b631-d070442987cf",
            "sourceColumn": "Industrial",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fd06806d-3a28-4c5f-9a6d-c49c7a5f00ec",
        "measures": [
          {
            "name": "Acción Botón Industrial",
            "expression": "IF([Rol Ind]=\"Si\",\"Menú Industrial\",\"Sin Permiso\")",
            "lineageTag": "6a3af137-e3bd-4aae-b79a-2aaf383f4917"
          },
          {
            "name": "Rol PA",
            "expression": "LOOKUPVALUE(Usuario[Rol Prod. Animal],Usuario[Usuario],USERNAME())",
            "lineageTag": "4eadddfd-62ad-4b26-9bf3-e2192b7d67f5"
          },
          {
            "name": "Acción Botón Prod. Animal",
            "expression": "IF([Rol PA]=\"Si\",\"Menú Prod. Animal\",\"Sin Permiso\")",
            "lineageTag": "88e3c34b-715a-4315-a3d3-c22f214b7ddf"
          },
          {
            "name": "Rol Ind",
            "expression": "LOOKUPVALUE(Usuario[Rol Industrial],Usuario[Usuario],USERNAME())",
            "lineageTag": "9964e860-820e-43fe-af62-8395cb854996"
          },
          {
            "name": "Transparente",
            "expression": "IF(TRUE(),\"#FFFFFF00\",\"#FFFFFF00\")",
            "lineageTag": "d04b38b4-3275-490f-99ce-0559e358afcd"
          }
        ],
        "partitions": [
          {
            "name": "Usuario-d17fade2-6a7f-42be-8696-f4f92951ffa5",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Excel.Workbook(Web.Contents(\"https://agrosuper.sharepoint.com/sites/GerenciaPlanificacion/BI/Documentos%20compartidos/Agristats/Automatizaci%C3%B3n%20Agristats/Usuarios.xlsx\"), null, true),",
                "    Usuario_Sheet = Origen{[Item=\"Usuario\",Kind=\"Sheet\"]}[Data],",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(Usuario_Sheet,{{\"Column1\", type text}, {\"Column2\", type text}}),",
                "    #\"Encabezados promovidos\" = Table.PromoteHeaders(#\"Tipo cambiado\", [PromoteAllScalars=true]),",
                "    #\"Tipo cambiado1\" = Table.TransformColumnTypes(#\"Encabezados promovidos\",{{\"Rol Industrial\", type text}})",
                "in",
                "    #\"Tipo cambiado1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "OrdenIndice",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e48a6cf3-9ef5-49e8-859c-9e6b73800efb",
            "sourceColumn": "Indice",
            "summarizeBy": "none"
          },
          {
            "name": "Orden Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d6c02b92-62fd-411f-8060-e5ef2b7ca1d7",
            "sourceColumn": "Orden Indice",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3af5cea4-953f-4558-aba7-3c5ca24b6d44",
        "partitions": [
          {
            "name": "OrdenIndice-8c573a6e-1957-4ce8-a91f-2f67d299b507",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Excel.Workbook(Web.Contents(\"https://agrosuper.sharepoint.com/sites/GerenciaPlanificacion/BI/Documentos%20compartidos/Agristats/Automatizaci%C3%B3n%20Agristats/Industrial/Maestra%20Industrial.xlsx\"), null, true),",
                "    OrdenIndice_Sheet = Origen{[Item=\"OrdenIndice\",Kind=\"Sheet\"]}[Data],",
                "    #\"Encabezados promovidos\" = Table.PromoteHeaders(OrdenIndice_Sheet, [PromoteAllScalars=true]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Encabezados promovidos\",{{\"Indice\", type text}, {\"Orden Indice\", Int64.Type}})",
                "in",
                "    #\"Tipo cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Indice Industrial Pollo",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Cod. Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9dd0e5a-f1f8-4710-98cb-da1a81336f09",
            "sourceColumn": "Cod. Indice",
            "summarizeBy": "none"
          },
          {
            "name": "Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4c9bef36-361a-4a28-bac7-e4885ade2059",
            "sourceColumn": "Indice",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "66bb9fea-7323-4b06-9659-1e40d2eff362",
        "partitions": [
          {
            "name": "Indice Industrial Pollo-9eaa7521-e62f-4b44-be68-5d978541cc9f",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = #\"Maestra Industrial\",",
                "    #\"Filas filtradas\" = Table.SelectRows(Origen, each ([sys_cd] = \"PROCE\")),",
                "    #\"Columnas quitadas\" = Table.RemoveColumns(#\"Filas filtradas\",{\"sys_cd\", \"Sector\", \"N Libro\", \"Descripción Libro\", \"Apertura Indice\", \"Desc Apertura Indice\"}),",
                "    #\"Duplicados quitados\" = Table.Distinct(#\"Columnas quitadas\", {\"Cod. Indice\"})",
                "in",
                "    #\"Duplicados quitados\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Orden Indice AA",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a202d790-ea55-4ee2-bc9a-6347fbc50c64",
            "sourceColumn": "Indice",
            "summarizeBy": "none"
          },
          {
            "name": "Orden Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e23f52ae-9c84-42e4-a04b-65221e5699ef",
            "sourceColumn": "Orden Indice",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "24790422-a98c-4091-82d3-cedddbff38b5",
        "partitions": [
          {
            "name": "Orden Indice AA-ae1f5e92-70ea-4b1e-980f-17c10b6d69e0",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Excel.Workbook(Web.Contents(\"https://agrosuper.sharepoint.com/sites/GerenciaPlanificacion/BI/Documentos%20compartidos/Agristats/Automatizaci%C3%B3n%20Agristats/Industrial/Maestra%20Industrial.xlsx\"), null, true),",
                "    #\"Orden Indice AA_Sheet\" = Origen{[Item=\"Orden Indice AA\",Kind=\"Sheet\"]}[Data],",
                "    #\"Encabezados promovidos\" = Table.PromoteHeaders(#\"Orden Indice AA_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Encabezados promovidos\",{{\"Indice\", type text}, {\"Orden Indice\", Int64.Type}})",
                "in",
                "    #\"Tipo cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Indice Industrial Cerdo",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Cod. Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "55f99e01-fe82-4f50-becd-1b41187ecf35",
            "sourceColumn": "Cod. Indice",
            "summarizeBy": "none"
          },
          {
            "name": "Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b14fdcc6-d241-45c2-858c-3902c0cd5369",
            "sourceColumn": "Indice",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3011dfa1-564a-45f0-92f9-b9502eff6ec9",
        "partitions": [
          {
            "name": "Indice Industrial Cerdo-af4f232e-8281-4017-85ca-b291715e467e",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = #\"Maestra Industrial\",",
                "    #\"Filas filtradas\" = Table.SelectRows(Origen, each ([sys_cd] = \"SWPRO\")),",
                "    #\"Columnas quitadas\" = Table.RemoveColumns(#\"Filas filtradas\",{\"sys_cd\", \"Sector\", \"N Libro\", \"Descripción Libro\", \"Apertura Indice\", \"Desc Apertura Indice\"}),",
                "    #\"Duplicados quitados\" = Table.Distinct(#\"Columnas quitadas\", {\"Cod. Indice\"})",
                "in",
                "    #\"Duplicados quitados\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Orden Indice AA CERDO",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4395233e-737d-4975-97cb-98a8bdcddb46",
            "sourceColumn": "Indice",
            "summarizeBy": "none"
          },
          {
            "name": "Orden Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "92769347-49d7-488b-9889-d9bbecb68686",
            "sourceColumn": "Orden Indice",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4a393e76-61ff-48bc-8e71-d3f2fd482f66",
        "partitions": [
          {
            "name": "Orden Indice AA CERDO-f847e592-651c-42f6-99fa-5eaf693271b7",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Excel.Workbook(Web.Contents(\"https://agrosuper.sharepoint.com/sites/GerenciaPlanificacion/BI/Documentos%20compartidos/Agristats/Automatizaci%C3%B3n%20Agristats/Industrial/Maestra%20Industrial.xlsx\"), null, true),",
                "    #\"Orden Indice AA_Sheet\" = Origen{[Item=\"Orden Indice AA CERDO\",Kind=\"Sheet\"]}[Data],",
                "    #\"Encabezados promovidos\" = Table.PromoteHeaders(#\"Orden Indice AA_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Encabezados promovidos\",{{\"Indice\", type text}, {\"Orden Indice\", Int64.Type}})",
                "in",
                "    #\"Tipo cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}